Repository open-mmlab/mmdeploy, pull requests merged in 2021-12, with the labels that each got.

#11 [Doc]: add openvino.md to index.rst
  docs/en/index.rst
Labels: documentation

#16 [Enhancement] support coverage
  .github/workflows/build.yml
Labels: enhancement

#15 [Docs] update acknowledgement and MMDeploy's short introduction
  README.md
  README_zh-CN.md
Labels: documentation

#25 [Docs] add switch-language
  docs/en/_static/css/readthedocs.css
  docs/en/_static/image/mmdeploy-logo.png
  docs/en/conf.py
  docs/en/index.rst
  docs/en/switch_language.md
  docs/zh_cn/_static/css/readthedocs.css
  docs/zh_cn/_static/image/mmdeploy-logo.png
  docs/zh_cn/conf.py
  docs/zh_cn/index.rst
  docs/zh_cn/switch_language.md
Labels: documentation

#31 [Docs] fix pplnn performance results for mmseg
  docs/en/benchmark.md
  docs/zh_cn/benchmark.md
Labels: documentation

#12 [Fix] Fix input names
  mmdeploy/apis/openvino/utils.py
  mmdeploy/apis/pytorch2onnx.py
  mmdeploy/backend/tensorrt/onnx2tensorrt.py
  mmdeploy/codebase/base/backend_model.py
  mmdeploy/codebase/mmcls/deploy/classification_model.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  mmdeploy/codebase/mmedit/deploy/super_resolution_model.py
  mmdeploy/codebase/mmocr/deploy/text_detection_model.py
  mmdeploy/codebase/mmocr/deploy/text_recognition_model.py
  mmdeploy/codebase/mmseg/deploy/segmentation_model.py
  mmdeploy/utils/__init__.py
  mmdeploy/utils/config_utils.py
  mmdeploy/utils/export_info.py
  mmdeploy/utils/test.py
  tests/test_apis/test_onnx2openvino.py
  tests/test_apis/test_torch2onnx.py
  tests/test_codebase/test_mmedit/test_mmedit_models.py
  tests/test_utils/test_util.py
  tools/deploy.py
Labels: WIP

#32 【Docs】fix docs
  README.md
  README_zh-CN.md
  docs/en/codebases/mmcls.md
  docs/en/codebases/mmdet.md
  docs/en/codebases/mmedit.md
  docs/en/codebases/mmocr.md
  docs/en/codebases/mmseg.md
  docs/zh_cn/conf.py
Labels: documentation
