Repository open-mmlab/mmdeploy, pull requests merged in 2022-04, with the labels that each got.

#336 [Fix] MMEditing cannot save results when testing
  mmdeploy/codebase/mmedit/deploy/super_resolution_model.py
Labels: bug

#365 Tutorial 03: torch2onnx
  docs/zh_cn/tutorials/chapter_03_pytorch2onnx.md
Labels: documentation

#234 【Docs】Add ipynb
  .pre-commit-config.yaml
  demo/tutorials/tutorials_1.ipynb
Labels: documentation

#371 [Enhance] remove expand from mmdet rewriter
  mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py
  mmdeploy/codebase/mmdet/deploy/utils.py
  mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py
  mmdeploy/codebase/mmdet/models/dense_heads/gfl_head.py
  mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py
  mmdeploy/codebase/mmdet/models/dense_heads/yolo_head.py
  mmdeploy/codebase/mmdet/models/roi_heads/bbox_head.py
  mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py
Labels: enhancement
