Repository open-mmlab/mmdeploy, pull requests merged in 2022-10, with the labels that each got.

#1158 Update timer
  mmdeploy/utils/timer.py
  tools/profiler.py
  tools/test.py
Labels: to 2.0

#1168 [Fix] fix layer norm when torch>=1.12
  mmdeploy/pytorch/ops/layer_norm.py
Labels: Bug:P0

#1169 [Fix 2.0] remove aten for torch1.12 on dev-1.x
  mmdeploy/pytorch/ops/layer_norm.py
Labels: Bug:P0

#1182 [Fix] Fix create input for dev-1.x
  mmdeploy/apis/calibration.py
  mmdeploy/codebase/mmcls/deploy/classification.py
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
Labels: Bug:P0

#1045 Rewrite Conv2dAdaptiveOps for conversion of EfficientNet (static shape)
  mmdeploy/mmcv/cnn/__init__.py
  mmdeploy/mmcv/cnn/conv2d_adaptive_padding.py
  tests/regression/mmcls.yml
  tests/test_mmcv/test_mmcv_cnn.py
Labels: to 2.0

#1122 update symbolic rewriter
  mmdeploy/core/rewriters/symbolic_rewriter.py
  tests/test_core/test_symbolic_register.py
Labels: to 2.0

#986 add batch inference in demo
  demo/csrc/CMakeLists.txt
  demo/csrc/c/batch_image_classification.cpp
  demo/csrc/c/batch_object_detection.cpp
Labels: enhancement

#1207 remove imports
  docs/en/04-supported-codebases/mmocr.md
  docs/zh_cn/04-supported-codebases/mmocr.md
  mmdeploy/apis/onnx/partition.py
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/core/optimizers/__init__.py
  mmdeploy/core/optimizers/optimize.py
Labels: to 2.0

#1144 [Enhancement] Update API for TensorRT8.4
  mmdeploy/backend/tensorrt/utils.py
Labels: to 2.0

#1186 [Feature] Add `Cond` node and pose tracker demo
  csrc/mmdeploy/archive/value_archive.h
  csrc/mmdeploy/graph/CMakeLists.txt
  csrc/mmdeploy/graph/cond.cpp
  csrc/mmdeploy/graph/cond.h
  demo/csrc/CMakeLists.txt
  demo/csrc/cpp/pose_tracker.cpp
  tests/test_csrc/CMakeLists.txt
  tests/test_csrc/graph/test_cond.cpp
  tests/test_csrc/graph/test_crnn.cpp
Labels: to 2.0
