Repository open-mmlab/mmdeploy, pull requests merged in 2022-12, with the labels that each got.

#1556 Cherry-pick #1352 to fix ops unittest seg-fault error
  csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/fuse_pass.cpp
  mmdeploy/mmcv/ops/roi_align.py
  tests/test_ops/test_ops.py
Labels: Bug:P0

#1518 [Fix] Fix onnx2ncnn.cpp bugs.
  csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
Labels: Bug:P0, dev-1.x

#1575 [Fix] Fix Mask R-CNN for multi-batch
  mmdeploy/apis/visualize.py
  mmdeploy/codebase/mmdet/models/roi_heads/test_mixins.py
  tools/deploy.py
Labels: Bug:P0, to 2.0

#1576 [Fix] Fix Mask R-CNN for multi-batch on dev-1.x
  mmdeploy/apis/visualize.py
  mmdeploy/codebase/mmdet/models/roi_heads/standard_roi_head.py
  tools/deploy.py
Labels: Bug:P0

#1573 Add softmax to cls model
  mmdeploy/codebase/mmcls/deploy/classification.py
  mmdeploy/codebase/mmcls/deploy/classification_model.py
  mmdeploy/codebase/mmcls/models/classifiers/base.py
  tests/test_codebase/test_mmcls/test_mmcls_models.py
Labels: bug
