Repository open-mmlab/mmdeploy, pull requests merged in 2022-03, with the labels that each got.

#150 [Enhancement] Make rewriter more powerful
  mmdeploy/codebase/mmdet/deploy/utils.py
  mmdeploy/core/rewriters/function_rewriter.py
  mmdeploy/core/rewriters/module_rewriter.py
  mmdeploy/core/rewriters/rewriter_manager.py
  mmdeploy/core/rewriters/rewriter_utils.py
  mmdeploy/core/rewriters/symbolic_rewriter.py
  mmdeploy/utils/__init__.py
  mmdeploy/utils/constants.py
  mmdeploy/utils/env.py
  tests/test_core/test_function_rewriter.py
  tests/test_core/test_rewriter_registry.py
  tests/test_core/test_rewriter_utils.py
  tests/test_utils/test_util.py
  tools/check_env.py
Labels: enhancement, refactoring

#176 [Docs]add "How to support new backends"中文翻译
  docs/zh_cn/tutorials/how_to_support_new_backends.md
Labels: documentation

#196 [Docs]: update docs and argument descriptions
  docs/en/supported_models.md
  docs/en/tutorials/how_to_convert_model.md
  docs/zh_cn/tutorials/how_to_convert_model.md
  tools/deploy.py
Labels: documentation

#181 Update supported mmseg models
  configs/mmseg/segmentation_ncnn_static.py
  configs/mmseg/segmentation_onnxruntime_static-1024x2048.py
  configs/mmseg/segmentation_onnxruntime_static-512x512.py
  configs/mmseg/segmentation_openvino_static-512x512.py
  configs/mmseg/segmentation_tensorrt-fp16_static-1024x1024.py
  configs/mmseg/segmentation_tensorrt-fp16_static-512x512.py
  configs/mmseg/segmentation_tensorrt-int8_static-1024x1024.py
  configs/mmseg/segmentation_tensorrt-int8_static-512x512.py
  configs/mmseg/segmentation_tensorrt_static-1024x1024.py
  configs/mmseg/segmentation_tensorrt_static-512x512.py
  docs/en/benchmark.md
  docs/en/codebases/mmseg.md
  docs/en/supported_models.md
  docs/zh_cn/benchmark.md
  mmdeploy/codebase/mmseg/models/decode_heads/__init__.py
  mmdeploy/codebase/mmseg/models/decode_heads/ema_head.py
  mmdeploy/codebase/mmseg/models/decode_heads/psp_head.py
  mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py
  mmdeploy/pytorch/functions/topk.py
  tests/test_codebase/test_mmseg/test_mmseg_models.py
Labels: enhancement

#199 fix unnecessary change of config for dynamic exporting
  mmdeploy/codebase/mmseg/deploy/segmentation.py
Labels: bug

#214 [Dostring]add example in apis docstring
  mmdeploy/apis/calibration.py
  mmdeploy/apis/extract_model.py
  mmdeploy/apis/inference.py
  mmdeploy/apis/pytorch2onnx.py
  mmdeploy/apis/visualize.py
  mmdeploy/backend/ncnn/onnx2ncnn.py
  mmdeploy/backend/openvino/onnx2openvino.py
  mmdeploy/backend/tensorrt/onnx2tensorrt.py
Labels: documentation

#103 [Features]Support mmdet3d
  .github/workflows/lint.yml
  configs/mmdet3d/voxel-detection/voxel-detection_dynamic.py
  configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime_dynamic.py
  configs/mmdet3d/voxel-detection/voxel-detection_openvino_dynamic.py
  configs/mmdet3d/voxel-detection/voxel-detection_static.py
  configs/mmdet3d/voxel-detection/voxel-detection_tensorrt_dynamic-kitti.py
  docs/en/codebases/mmdet3d.md
  docs/en/supported_models.md
  mmdeploy/apis/pytorch2onnx.py
  mmdeploy/apis/visualize.py
  mmdeploy/backend/openvino/wrapper.py
  mmdeploy/codebase/mmdet3d/__init__.py
  mmdeploy/codebase/mmdet3d/deploy/__init__.py
  mmdeploy/codebase/mmdet3d/deploy/mmdetection3d.py
  mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py
  mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py
  mmdeploy/codebase/mmdet3d/models/__init__.py
  mmdeploy/codebase/mmdet3d/models/base.py
  mmdeploy/codebase/mmdet3d/models/pillar_encode.py
  mmdeploy/codebase/mmdet3d/models/pillar_scatter.py
  mmdeploy/codebase/mmdet3d/models/voxelnet.py
  mmdeploy/utils/constants.py
  tests/test_codebase/test_mmdet3d/data/kitti/kitti_000008.bin
  tests/test_codebase/test_mmdet3d/data/kitti/kitti_infos_val.pkl
  tests/test_codebase/test_mmdet3d/data/model_cfg.py
  tests/test_codebase/test_mmdet3d/test_mmdet3d_models.py
  tests/test_codebase/test_mmdet3d/test_voxel_detection.py
  tests/test_codebase/test_mmdet3d/test_voxel_detection_model.py
Labels: planned feature

#167 [Enhancement] Optimize multilevel roi align
  csrc/backend_ops/tensorrt/common/common_cuda_helper.hpp
  csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align.cpp
  csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align.hpp
  csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align_kernel.cu
  csrc/backend_ops/tensorrt/multi_level_roi_align/trt_multi_level_roi_align_kernel.hpp
  mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py
  tests/test_ops/test_ops.py
Labels: enhancement

#168 [Enhancement] Update pad logic in detection heads
  mmdeploy/codebase/mmdet/__init__.py
  mmdeploy/codebase/mmdet/deploy/__init__.py
  mmdeploy/codebase/mmdet/deploy/utils.py
  mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py
  mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py
  mmdeploy/codebase/mmdet/models/dense_heads/yolo_head.py
  tests/test_codebase/test_mmdet/test_mmdet_utils.py
Labels: enhancement

#232 [Fix] fix l2norm test
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: Bug:P1

#178 [Enhancement] Additional arguments support for OpenVINO Model Optimizer
  docs/en/backends/openvino.md
  docs/en/codebases/mmpose.md
  mmdeploy/apis/calibration.py
  mmdeploy/apis/extract_model.py
  mmdeploy/apis/inference.py
  mmdeploy/apis/openvino/__init__.py
  mmdeploy/apis/openvino/utils.py
  mmdeploy/apis/pytorch2onnx.py
  mmdeploy/apis/visualize.py
  mmdeploy/backend/ncnn/onnx2ncnn.py
  mmdeploy/backend/openvino/__init__.py
  mmdeploy/backend/openvino/onnx2openvino.py
  mmdeploy/backend/openvino/utils.py
  mmdeploy/backend/tensorrt/onnx2tensorrt.py
  mmdeploy/utils/test.py
  tests/test_apis/test_onnx2openvino.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
  tools/deploy.py
Labels: enhancement

#208 Add DefaultFormatBundle
  csrc/preprocess/cpu/CMakeLists.txt
  csrc/preprocess/cpu/default_format_bundle_impl.cpp
  csrc/preprocess/cuda/CMakeLists.txt
  csrc/preprocess/cuda/default_format_bundle_impl.cpp
  csrc/preprocess/transform/CMakeLists.txt
  csrc/preprocess/transform/collect.h
  csrc/preprocess/transform/crop.h
  csrc/preprocess/transform/default_format_bundle.cpp
  csrc/preprocess/transform/default_format_bundle.h
  csrc/preprocess/transform/image2tensor.h
  csrc/preprocess/transform/load.h
  csrc/preprocess/transform/normalize.h
  mmdeploy/utils/export_info.py
  tests/test_csrc/preprocess/test_default_format_bundle.cpp
Labels: SDK

#205 [Enhancement] TensorRT DCN support
  csrc/backend_ops/tensorrt/common/common_cuda_helper.hpp
  csrc/backend_ops/tensorrt/common_impl/trt_cuda_helper.cu
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv.cpp
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv.hpp
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv_kernel.cu
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv_kernel.cuh
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv_kernel.hpp
  mmdeploy/mmcv/ops/deform_conv.py
  tests/test_ops/test_ops.py
Labels: enhancement, TensorRT

#250 [Fix] add support for headless device
  tools/deploy.py
Labels: bug

#272 [Bug] compatible with torch 1.11
  mmdeploy/apis/pytorch2onnx.py
Labels: bug

#164 Ncnn demo sdk
  configs/_base_/backends/ncnn.py
  csrc/codebase/mmdet/object_detection.cpp
  csrc/codebase/mmdet/object_detection.h
  csrc/core/CMakeLists.txt
  csrc/core/utils/stacktrace.cpp
  csrc/model/CMakeLists.txt
  csrc/net/ncnn/ncnn_net.cpp
  csrc/preprocess/transform/pad.cpp
  docs/en/build/android.md
  docs/zh_cn/build/android.md
  mmdeploy/utils/export_info.py
Labels: enhancement, SDK, Android

#282 [Fix] Fix ncnn example find package bugs.
  cmake/MMDeployConfig.cmake.in
  docs/en/build/android.md
  docs/zh_cn/build/android.md
Labels: Bug:P0
