Repository open-mmlab/mmdeploy, pull requests merged in 2022-07, with the labels that each got.

#692 [Fix] fix ssd ncnn ut
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: Bug:P1, Unittest

#698 [Fix] Fix android build
  csrc/mmdeploy/apis/java/native/CMakeLists.txt
  docs/en/01-how-to-build/android.md
  docs/zh_cn/01-how-to-build/android.md
Labels: bug, documentation

#754 add version control
  mmdeploy/pytorch/ops/pad.py
Labels: bug

#753 fix satrn for ORT
  mmdeploy/pytorch/functions/__init__.py
  mmdeploy/pytorch/functions/masked_fill.py
  tests/test_pytorch/test_pytorch_functions.py
Labels: bug

#773 Fix markdown table rendering failure in readthedocs
  requirements/docs.txt
Labels: documentation

#755 [Fix] reduce log verbosity & improve error reporting
  csrc/mmdeploy/apis/c/mmdeploy/executor.cpp
  csrc/mmdeploy/apis/c/mmdeploy/handle.h
  csrc/mmdeploy/apis/java/native/mmdeploy_Classifier.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_Detector.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_PoseDetector.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_Restorer.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_Segmentor.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_TextDetector.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_TextRecognizer.cpp
  csrc/mmdeploy/codebase/common.h
  csrc/mmdeploy/codebase/mmocr/dbnet.cpp
  csrc/mmdeploy/codebase/mmocr/panet.cpp
  csrc/mmdeploy/codebase/mmocr/psenet.cpp
  csrc/mmdeploy/core/model.cpp
  csrc/mmdeploy/core/registry.cpp
  csrc/mmdeploy/core/registry.h
  csrc/mmdeploy/core/status_code.cpp
  csrc/mmdeploy/device/cuda/cuda_device.cpp
  csrc/mmdeploy/execution/bulk.h
  csrc/mmdeploy/execution/schedulers/dynamic_batch_scheduler.h
  csrc/mmdeploy/graph/common.h
  csrc/mmdeploy/graph/pipeline.cpp
  csrc/mmdeploy/graph/task.cpp
  csrc/mmdeploy/model/zip_model_impl.cpp
  csrc/mmdeploy/net/net_module.cpp
  csrc/mmdeploy/net/ort/ort_net.cpp
  csrc/mmdeploy/net/ppl/ppl_net.cpp
  csrc/mmdeploy/net/trt/trt_net.cpp
  csrc/mmdeploy/preprocess/transform/compose.cpp
  csrc/mmdeploy/preprocess/transform/transform.h
  csrc/mmdeploy/preprocess/transform_module.cpp
Labels: SDK

#751 [Fix][P0] Fix for torch1.12
  mmdeploy/apis/onnx/optimizer.py
  mmdeploy/core/rewriters/rewriter_utils.py
Labels: Bug:P0

#785 [Fix] fix check env
  tools/check_env.py
Labels: bug

#762 [Fix] Support macOS build
  cmake/MMDeploy.cmake
  csrc/mmdeploy/backend_ops/onnxruntime/CMakeLists.txt
  csrc/mmdeploy/codebase/mmocr/cpu/CMakeLists.txt
  csrc/mmdeploy/core/CMakeLists.txt
  csrc/mmdeploy/model/CMakeLists.txt
  demo/csrc/CMakeLists.txt
  tests/test_csrc/CMakeLists.txt
  tests/test_csrc/core/test_execution.cpp
Labels: SDK
