Repository open-mmlab/mmdeploy, pull requests merged in 2022-11, with the labels that each got.

#1261 [Enhancement] Avoid copying dense arrays in C API
  csrc/mmdeploy/apis/c/mmdeploy/detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/restorer.cpp
  csrc/mmdeploy/apis/c/mmdeploy/segmentor.cpp
  csrc/mmdeploy/core/mpl/structure.h
Labels: SDK

#1345 [Bug] fix suffix caused by cherry-pick
  mmdeploy/backend/sdk/export_info.py
Labels: bug

#1347 [Docs] Sync mmcls mmedit docstring 2.0
  docs/en/03-benchmark/benchmark.md
  docs/en/03-benchmark/benchmark_edge.md
  docs/en/03-benchmark/quantization.md
  docs/en/04-supported-codebases/mmcls.md
  docs/en/04-supported-codebases/mmedit.md
  docs/zh_cn/03-benchmark/benchmark.md
  docs/zh_cn/03-benchmark/benchmark_edge.md
  docs/zh_cn/03-benchmark/quantization.md
  docs/zh_cn/04-supported-codebases/mmcls.md
  docs/zh_cn/04-supported-codebases/mmedit.md
  mmdeploy/codebase/mmcls/deploy/classification.py
  mmdeploy/codebase/mmcls/deploy/classification_model.py
  mmdeploy/codebase/mmcls/models/utils/attention.py
  mmdeploy/codebase/mmedit/deploy/mmediting.py
  mmdeploy/codebase/mmedit/deploy/super_resolution.py
  mmdeploy/codebase/mmedit/deploy/super_resolution_model.py
Labels: documentation

#1419 [Fix] Fix det_pose demo
  demo/csrc/c/det_pose.cpp
Labels: SDK

#1366 [Fix] Relax module adapter template constraints
  csrc/mmdeploy/codebase/mmdet/yolo_head.cpp
  csrc/mmdeploy/codebase/mmdet/yolo_head.h
  csrc/mmdeploy/experimental/module_adapter.h
Labels: SDK
