Repository open-mmlab/mmdeploy, pull requests merged in 2022-05, with the labels that each got.

#331 [Fix]fix pillarencode
  mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py
  mmdeploy/codebase/mmdet3d/models/pillar_encode.py
Labels: enhancement

#451 [Fix] Fix display bugs for windows
  tools/deploy.py
Labels: Bug:P1

#483 [Fix] set optional arg a default value
  tools/deploy.py
Labels: bug

#468 [Enhancement] Support DeformConv TensorRT fp16
  csrc/backend_ops/tensorrt/common_impl/trt_cuda_helper.cu
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv.cpp
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv_kernel.cu
  csrc/backend_ops/tensorrt/deform_conv/trt_deform_conv_kernel.cuh
Labels: enhancement

#457 [Feature] Support reppoints TensorRT
  docs/en/benchmark.md
  docs/en/codebases/mmdet.md
  docs/zh_cn/03-benchmark/benchmark.md
  docs/zh_cn/03-benchmark/supported_models.md
  mmdeploy/codebase/mmdet/models/dense_heads/__init__.py
  mmdeploy/codebase/mmdet/models/dense_heads/reppoints_head.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: enhancement

#419 [refactor][API2.0] Add onnx export and jit trace
  mmdeploy/apis/__init__.py
  mmdeploy/apis/core/__init__.py
  mmdeploy/apis/core/pipeline_manager.py
  mmdeploy/apis/onnx/__init__.py
  mmdeploy/apis/onnx/export.py
  mmdeploy/apis/pytorch2onnx.py
  mmdeploy/apis/pytorch2torchscript.py
  mmdeploy/apis/torch_jit/__init__.py
  mmdeploy/apis/torch_jit/trace.py
  mmdeploy/utils/logging.py
  mmdeploy/utils/test.py
  mmdeploy/utils/utils.py
  tests/test_apis/test_torch2onnx.py
  tests/test_backend/test_wrapper.py
  tests/test_utils/test_util.py
  tools/deploy.py
Labels: refactoring

#433 [Refactor][API2.0] Api partition calibration
  mmdeploy/apis/__init__.py
  mmdeploy/apis/calibration.py
  mmdeploy/apis/extract_model.py
  mmdeploy/apis/onnx/__init__.py
  mmdeploy/apis/onnx/partition.py
  mmdeploy/apis/pytorch2torchscript.py
  mmdeploy/apis/utils/__init__.py
  mmdeploy/apis/utils/calibration.py
  mmdeploy/apis/utils/utils.py
  tests/test_apis/test_calibration.py
  tests/test_apis/test_extract.py
  tests/test_apis/test_torch2torchscript.py
  tools/deploy.py
  tools/extract.py
Labels: refactoring
