Repository open-mmlab/mmdeploy, pull requests merged in 2022-06, with the labels that each got.

#390 [Enhancement] Add ONNX passes support
  csrc/backend_ops/torchscript/optimizer/bind.cpp
  csrc/backend_ops/torchscript/optimizer/ir/subgraph_matcher.cpp
  csrc/backend_ops/torchscript/optimizer/ir/subgraph_matcher.h
  csrc/backend_ops/torchscript/optimizer/passes/onnx/flatten_cls_head.cpp
  csrc/backend_ops/torchscript/optimizer/passes/onnx/flatten_cls_head.h
  csrc/backend_ops/torchscript/optimizer/passes/onnx/merge_shape_concate.cpp
  csrc/backend_ops/torchscript/optimizer/passes/onnx/merge_shape_concate.h
  csrc/backend_ops/torchscript/optimizer/passes/onnx/onnx_peephole.cpp
  csrc/backend_ops/torchscript/optimizer/passes/onnx/onnx_peephole.h
  csrc/backend_ops/torchscript/optimizer/passes/onnx/utils.h
  docs/en/experimental/onnx_optimizer.md
  mmdeploy/apis/onnx/export.py
  mmdeploy/apis/onnx/optimizer.py
  mmdeploy/apis/onnx/passes/__init__.py
  mmdeploy/apis/onnx/passes/optimize_onnx.py
  tests/test_apis/test_onnx_passes.py
Labels: enhancement

#562 [Fix] disable onnx export optimizer for 0.5.0
  csrc/backend_ops/torchscript/optimizer/passes/onnx/onnx_peephole.cpp
  mmdeploy/apis/onnx/export.py
Labels: Bug:P0

#605 [Fix ]fix ncnn textdet
  csrc/mmdeploy/net/ncnn/ncnn_net.cpp
Labels: Bug:P0

#604 [Fix] adapt mmocr different versions
  mmdeploy/codebase/mmocr/deploy/text_recognition_model.py
Labels: Bug:P0

#635 [Fix] Reduce mmcls version dependency
  mmdeploy/codebase/mmcls/models/backbones/shufflenet_v2.py
  mmdeploy/codebase/mmcls/models/backbones/vision_transformer.py
Labels: Bug:P1

#626 [Enhancement] Fix ncnn unittest
  mmdeploy/codebase/mmdet/models/backbones.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: Bug:P2

#563 Add java apis and demos
  .github/scripts/test_java_demo.py
  .github/workflows/java_api.yml
  .gitignore
  CMakeLists.txt
  csrc/mmdeploy/apis/java/CMakeLists.txt
  csrc/mmdeploy/apis/java/README.md
  csrc/mmdeploy/apis/java/mmdeploy/Classifier.java
  csrc/mmdeploy/apis/java/mmdeploy/DataType.java
  csrc/mmdeploy/apis/java/mmdeploy/Detector.java
  csrc/mmdeploy/apis/java/mmdeploy/InstanceMask.java
  csrc/mmdeploy/apis/java/mmdeploy/Mat.java
  csrc/mmdeploy/apis/java/mmdeploy/PixelFormat.java
  csrc/mmdeploy/apis/java/mmdeploy/PointF.java
  csrc/mmdeploy/apis/java/mmdeploy/PoseDetector.java
  csrc/mmdeploy/apis/java/mmdeploy/Rect.java
  csrc/mmdeploy/apis/java/mmdeploy/Restorer.java
  csrc/mmdeploy/apis/java/mmdeploy/Segmentor.java
  csrc/mmdeploy/apis/java/mmdeploy/TextDetector.java
  csrc/mmdeploy/apis/java/mmdeploy/TextRecognizer.java
  csrc/mmdeploy/apis/java/native/CMakeLists.txt
  csrc/mmdeploy/apis/java/native/common.h
  csrc/mmdeploy/apis/java/native/mmdeploy_Classifier.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_Classifier.h
  csrc/mmdeploy/apis/java/native/mmdeploy_Detector.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_Detector.h
  csrc/mmdeploy/apis/java/native/mmdeploy_PoseDetector.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_PoseDetector.h
  csrc/mmdeploy/apis/java/native/mmdeploy_Restorer.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_Restorer.h
  csrc/mmdeploy/apis/java/native/mmdeploy_Segmentor.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_Segmentor.h
  csrc/mmdeploy/apis/java/native/mmdeploy_TextDetector.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_TextDetector.h
  csrc/mmdeploy/apis/java/native/mmdeploy_TextRecognizer.cpp
  csrc/mmdeploy/apis/java/native/mmdeploy_TextRecognizer.h
  demo/java/ImageClassification.java
  demo/java/ImageRestorer.java
  demo/java/ImageSegmentation.java
  demo/java/ObjectDetection.java
  demo/java/Ocr.java
  demo/java/PoseDetection.java
  demo/java/README.md
  demo/java/Utils.java
  docs/en/01-how-to-build/android.md
  docs/en/01-how-to-build/linux-x86_64.md
  docs/zh_cn/01-how-to-build/android.md
  docs/zh_cn/01-how-to-build/linux-x86_64.md
Labels: SDK, java
