Repository open-mmlab/mmdeploy, pull requests merged in 2022-01, with the labels that each got.

#36 [Refactoring]: Add get_dynamic_axes.
  mmdeploy/apis/pytorch2onnx.py
  mmdeploy/utils/__init__.py
  mmdeploy/utils/config_utils.py
  mmdeploy/utils/test.py
  tests/test_apis/test_onnx2openvino.py
  tests/test_utils/test_util.py
Labels: refactoring

#47 [Documents] ncnn version fix at 1208.
  docs/en/backends/ncnn.md
Labels: documentation

#42 [Fix] Avoid outputing empty tensor in NMS
  mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py
  tests/test_codebase/test_mmdet/test_mmdet_core.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
  tests/test_ops/test_ops.py
Labels: Bug:P1, WIP

#50 [Enhancement] dump cls_name
  mmdeploy/utils/export_info.py
Labels: enhancement

#33 [Fix] Support MMDet custom dataset
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  tests/test_codebase/test_mmdet/test_object_detection_model.py
Labels: Bug:P3

#24 [Enhancement] use mmcv.utils.get_logger
  demo/demo_rewrite.py
  mmdeploy/__init__.py
  mmdeploy/apis/extract_model.py
  mmdeploy/backend/ncnn/wrapper.py
  mmdeploy/backend/onnxruntime/wrapper.py
  mmdeploy/backend/openvino/onnx2openvino.py
  mmdeploy/backend/pplnn/wrapper.py
  mmdeploy/backend/tensorrt/init_plugins.py
  mmdeploy/backend/tensorrt/utils.py
  mmdeploy/codebase/base/task.py
  mmdeploy/codebase/mmcls/deploy/classification.py
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/codebase/mmedit/deploy/super_resolution.py
  mmdeploy/codebase/mmocr/deploy/text_detection.py
  mmdeploy/codebase/mmocr/deploy/text_recognition.py
  mmdeploy/codebase/mmseg/deploy/segmentation.py
  mmdeploy/core/optimizers/optimize.py
  mmdeploy/core/rewriters/function_rewriter.py
  mmdeploy/core/rewriters/symbolic_rewriter.py
  mmdeploy/pytorch/functions/interpolate.py
  mmdeploy/utils/__init__.py
  mmdeploy/utils/export_info.py
  mmdeploy/utils/utils.py
  tests/test_utils/test_util.py
  tools/check_env.py
  tools/deploy.py
  tools/extract.py
  tools/onnx2ncnn.py
  tools/onnx2pplnn.py
  tools/onnx2tensorrt.py
  tools/torch2onnx.py
Labels: enhancement

#57 [Fix]: dynamic shape not valid in mmseg
  mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py
Labels: bug

#43 [Unittest] Add L2Norm unittest for default backend.
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: Unittest

#49 [Fix] Fix TensorRT 7 SSD
  mmdeploy/codebase/mmdet/models/necks.py
Labels: bug

#20 [Fix] move target_wrapper into utils
  mmdeploy/utils/__init__.py
  mmdeploy/utils/utils.py
  tests/test_utils/test_util.py
  tools/deploy.py
Labels: Bug:P2

#60 [Fix] Fix details of MMCodebase
  mmdeploy/codebase/base/mmcodebase.py
  mmdeploy/codebase/mmcls/deploy/mmclassification.py
Labels: Bug:P3

#59 Remove partition configs and docs
  configs/mmdet/detection/single-stage_partition_ncnn_static.py
  configs/mmdet/detection/single-stage_partition_onnxruntime_dynamic.py
  configs/mmdet/detection/single-stage_partition_onnxruntime_static.py
  configs/mmdet/detection/single-stage_partition_tensorrt_dynamic-320x320-1344x1344.py
  configs/mmdet/detection/two-stage_partition_onnxruntime_dynamic.py
  configs/mmdet/detection/two-stage_partition_onnxruntime_static.py
  configs/mmdet/detection/two-stage_partition_tensorrt-fp16_dynamic-320x320-1344x1344.py
  configs/mmdet/detection/two-stage_partition_tensorrt-int8_dynamic-320x320-1344x1344.py
  configs/mmdet/detection/two-stage_partition_tensorrt_dynamic-320x320-1344x1344.py
  docs/en/tutorials/how_to_write_config.md
Labels: enhancement

#61 [Enhancement]: Remove deepcopy in patch_model
  mmdeploy/core/rewriters/module_rewriter.py
  mmdeploy/core/rewriters/rewriter_manager.py
  tests/test_core/test_module_rewriter.py
Labels: enhancement

#58 [Fix] Fixed device_id in tools/test.py for the CPU.
  mmdeploy/backend/openvino/wrapper.py
  mmdeploy/utils/device.py
  tests/test_utils/test_util.py
  tools/test.py
Labels: bug

#29 [Feature] add yolox ncnn
  configs/mmdet/detection/single-stage_ncnn_static-416x416.py
  docs/en/benchmark.md
  docs/en/codebases/mmdet.md
  docs/en/supported_models.md
  docs/zh_cn/benchmark.md
  mmdeploy/backend/ncnn/wrapper.py
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  mmdeploy/codebase/mmdet/models/__init__.py
  mmdeploy/codebase/mmdet/models/backbones.py
  mmdeploy/codebase/mmdet/models/dense_heads/__init__.py
  mmdeploy/codebase/mmdet/models/dense_heads/yolox_head.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: enhancement

#71 [Doc] Nano benchmark and tutorial
  docs/en/backends/tensorrt.md
  docs/en/benchmark.md
  docs/en/index.rst
  docs/en/tutorials/how_to_install_mmdeploy_on_jetsons.md
  docs/zh_cn/benchmark.md
Labels: documentation

#80 [Fix] fix missing deploy_core
  demo/csrc/CMakeLists.txt
Labels: bug

#84 [Docs] Fix links in Chinese doc
  docs/zh_cn/build.md
  docs/zh_cn/get_started.md
  docs/zh_cn/tutorials/how_to_convert_model.md
Labels: bug, documentation

#67 [Feature] Add docker files
  docker/CPU/Dockerfile
  docker/GPU/Dockerfile
  docs/en/build.md
  docs/en/index.rst
  docs/en/tutorials/how_to_use_docker.md
  docs/zh_cn/build.md
  docs/zh_cn/index.rst
  docs/zh_cn/tutorials/how_to_use_docker.md
Labels: planned feature

#96 [Doc] Update FAQ for TensorRT
  docs/en/faq.md
  mmdeploy/backend/tensorrt/wrapper.py
Labels: enhancement

#102 [Docs]: Update doc for openvino installation
  docs/en/backends/openvino.md
  docs/en/build.md
  docs/en/get_started.md
  docs/zh_cn/build.md
  docs/zh_cn/get_started.md
Labels: documentation

#99 [Enhancement] Simplify non batch nms
  mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py
Labels: enhancement
