Repository open-mmlab/mmdeploy, pull requests merged in 2022-02, with the labels that each got.

#115 [Enhancement] Support mmocr v0.4+
  mmdeploy/codebase/mmcls/deploy/classification_model.py
  mmdeploy/codebase/mmocr/deploy/mmocr.py
  mmdeploy/codebase/mmocr/deploy/text_detection_model.py
  mmdeploy/codebase/mmocr/deploy/text_recognition_model.py
Labels: enhancement

#123 fix onnxruntime wrapper for gpu inference
  mmdeploy/backend/onnxruntime/wrapper.py
Labels: bug

#125 [Enhancement] Fix tests for OpenVINO with Python 3.6
  docs/en/tutorials/how_to_support_new_backends.md
  mmdeploy/backend/openvino/onnx2openvino.py
Labels: enhancement

#147 Create How to support new model.md
  docs/zh_cn/tutorials/how_to_support_new_model.md
Labels: documentation

#109 [Doc] Update Nvidia Jetson TX2 benchmark
  docs/en/benchmark.md
  docs/zh_cn/benchmark.md
Labels: documentation

#137 [Docs] Update Chinese how_to_write_config.md
  docs/zh_cn/tutorials/how_to_write_config.md
Labels: documentation

#94 [Feature]: Support mmpose
  .github/workflows/build.yml
  configs/mmpose/pose-detection_ncnn_static-256x192.py
  configs/mmpose/pose-detection_onnxruntime_static.py
  configs/mmpose/pose-detection_openvino_static-256x192.py
  configs/mmpose/pose-detection_pplnn_static-256x192.py
  configs/mmpose/pose-detection_static.py
  configs/mmpose/pose-detection_tensorrt-fp16_static-256x192.py
  configs/mmpose/pose-detection_tensorrt-int8_static-256x192.py
  configs/mmpose/pose-detection_tensorrt_static-256x192.py
  demo/resources/human-pose.jpg
  docs/en/benchmark.md
  docs/en/codebases/mmpose.md
  docs/zh_cn/benchmark.md
  mmdeploy/codebase/mmedit/deploy/mmediting.py
  mmdeploy/codebase/mmpose/__init__.py
  mmdeploy/codebase/mmpose/deploy/__init__.py
  mmdeploy/codebase/mmpose/deploy/mmpose.py
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
  mmdeploy/codebase/mmpose/deploy/pose_detection_model.py
  mmdeploy/codebase/mmpose/models/__init__.py
  mmdeploy/codebase/mmpose/models/backbones/__init__.py
  mmdeploy/codebase/mmpose/models/backbones/litehrnet.py
  mmdeploy/codebase/mmpose/models/detectors/__init__.py
  mmdeploy/codebase/mmpose/models/detectors/top_down.py
  mmdeploy/codebase/mmpose/models/heads/__init__.py
  mmdeploy/codebase/mmpose/models/heads/topdown_heatmap_multi_stage_head.py
  mmdeploy/codebase/mmpose/models/heads/topdown_heatmap_simple_head.py
  mmdeploy/utils/constants.py
  requirements/optional.txt
  tests/test_codebase/test_mmcls/test_classification_model.py
  tests/test_codebase/test_mmcls/test_mmcls_models.py
  tests/test_codebase/test_mmpose/data/annotations/person_keypoints_val2017.json
  tests/test_codebase/test_mmpose/data/model.py
  tests/test_codebase/test_mmpose/test_mmpose_models.py
  tests/test_codebase/test_mmpose/test_pose_detection.py
  tests/test_codebase/test_mmpose/test_pose_detection_model.py
Labels: planned feature

#143 Lock pplcv to v0.6.1
  docker/GPU/Dockerfile
  docs/en/build.md
  docs/zh_cn/build.md
Labels: documentation

#152 [Enhancement] optimize delta2bboxes
  mmdeploy/codebase/mmdet/core/bbox/delta_xywh_bbox_coder.py
Labels: enhancement

#171 [Docs]add mmrotate link
  README.md
  README_zh-CN.md
Labels: documentation

#175 [FIX] update docs and configs about openvino ssd deployment
  configs/mmdet/_base_/base_openvino_dynamic-300x300.py
  configs/mmdet/detection/detection_openvino_dynamic-300x300.py
  docs/en/backends/openvino.md
Labels: documentation

#169 support export hardsigmoid in torch<=1.8
  mmdeploy/pytorch/ops/__init__.py
  mmdeploy/pytorch/ops/hardsigmoid.py
  tests/test_pytorch/test_pytorch_ops.py
Labels: enhancement
