Repository open-mmlab/mmdeploy, pull requests merged in 2022-08, with the labels that each got.

#890 [Feature] TorchScript SDK backend
  cmake/cuda.cmake
  csrc/mmdeploy/net/CMakeLists.txt
  csrc/mmdeploy/net/torchscript/CMakeLists.txt
  csrc/mmdeploy/net/torchscript/torch_net.cpp
  csrc/mmdeploy/net/torchscript/torch_net.h
  mmdeploy/backend/sdk/export_info.py
Labels: SDK

#941 [Bug] fix setitem with scalar or single element tensor
  mmdeploy/pytorch/functions/tensor_setitem.py
  tests/test_pytorch/test_pytorch_functions.py
Labels: bug

#924 [Enhancement] Support DETR
  docs/en/03-benchmark/benchmark.md
  docs/en/03-benchmark/supported_models.md
  docs/en/04-supported-codebases/mmdet.md
  docs/zh_cn/03-benchmark/benchmark.md
  docs/zh_cn/03-benchmark/supported_models.md
  docs/zh_cn/04-supported-codebases/mmdet.md
  mmdeploy/codebase/mmdet/models/dense_heads/__init__.py
  mmdeploy/codebase/mmdet/models/dense_heads/detr_head.py
  mmdeploy/pytorch/functions/__init__.py
  mmdeploy/pytorch/functions/multi_head_attention_forward.py
  tests/regression/mmdet.yml
  tests/test_codebase/test_mmdet/test_mmdet_models.py
  tests/test_pytorch/test_pytorch_functions.py
Labels: enhancement

#951 [Fix] fix ut failed
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: Bug:P0, Unittest
