Repository open-mmlab/mmdeploy, pull requests merged in 2022-09, with the labels that each got.

#1044 [BUG P0] Fix CoreML Two Stage detector
  mmdeploy/backend/coreml/ops.py
  mmdeploy/codebase/mmdet/models/dense_heads/rpn_head.py
  mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py
Labels: Bug:P0

#1046 [Bug] fix two stage batch dynamic
  mmdeploy/codebase/mmdet/models/roi_heads/test_mixins.py
Labels: bug

#979 [Fix] Sync codebase 2.0
  mmdeploy/apis/pytorch2torchscript.py
  mmdeploy/backend/sdk/export_info.py
  mmdeploy/codebase/mmcls/deploy/classification.py
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  mmdeploy/codebase/mmdet/models/dense_heads/gfl_head.py
  mmdeploy/codebase/mmdet/models/detectors/single_stage.py
  tests/test_apis/test_calibration.py
  tests/test_apis/test_onnx2openvino.py
  tests/test_apis/test_torch2torchscript.py
  tests/test_backend/test_wrapper.py
  tests/test_codebase/test_mmcls/data/imgs/val/blank.jpg
  tests/test_codebase/test_mmcls/test_classification.py
  tests/test_codebase/test_mmcls/test_classification_model.py
  tests/test_codebase/test_mmcls/test_mmcls_models.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
  tests/test_codebase/test_mmdet/test_object_detection.py
  tests/test_codebase/test_mmdet/test_object_detection_model.py
  tests/test_mmcv/test_mmcv_cnn.py
  tests/test_ops/utils.py
  tests/test_pytorch/test_pytorch_functions.py
  tests/test_utils/test_util.py
  tools/check_env.py
  tools/test.py
Labels: enhancement, mmdet

#1017 [2.0] Support mmedit 2.0
  mmdeploy/backend/sdk/export_info.py
  mmdeploy/codebase/base/task.py
  mmdeploy/codebase/mmedit/__init__.py
  mmdeploy/codebase/mmedit/deploy/mmediting.py
  mmdeploy/codebase/mmedit/deploy/super_resolution.py
  mmdeploy/codebase/mmedit/deploy/super_resolution_model.py
  mmdeploy/codebase/mmedit/models/__init__.py
  mmdeploy/codebase/mmedit/models/base_models/__init__.py
  mmdeploy/codebase/mmedit/models/base_models/base_edit_model.py
  tests/regression/mmedit.yml
  tests/test_codebase/test_mmedit/data/model.py
  tests/test_codebase/test_mmedit/data/test_ann.txt
  tests/test_codebase/test_mmedit/test_mmedit_models.py
  tests/test_codebase/test_mmedit/test_super_resolution.py
  tests/test_codebase/test_mmedit/test_super_resolution_model.py
  tools/regression_test.py
  tools/test.py
Labels: enhancement

#1082 [Fix] fix torchscript
  mmdeploy/apis/pytorch2torchscript.py
  mmdeploy/apis/torch_jit/trace.py
  mmdeploy/codebase/mmocr/models/text_detection/single_stage_text_detector.py
Labels: Bug:P0

#1085 [Fix] border -> pad_param
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
Labels: Bug:P0

#1056 [Fix] Fix mmcls for cifar10 config on dev-1.x
  mmdeploy/codebase/mmcls/deploy/classification.py
Labels: Bug:P0

#1088 [Enhancement 2.0] mmdeploy for mmyolo
  csrc/mmdeploy/codebase/mmocr/short_scale_aspect_jitter.cpp
  mmdeploy/apis/utils/utils.py
  mmdeploy/codebase/__init__.py
  mmdeploy/codebase/base/mmcodebase.py
  mmdeploy/codebase/base/task.py
  mmdeploy/codebase/mmcls/deploy/classification.py
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/codebase/mmdet3d/deploy/mmdetection3d.py
  mmdeploy/codebase/mmedit/deploy/mmediting.py
  mmdeploy/codebase/mmocr/deploy/mmocr.py
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
  mmdeploy/codebase/mmseg/deploy/segmentation.py
  mmdeploy/utils/config_utils.py
  requirements/runtime.txt
  tests/test_utils/test_util.py
Labels: enhancement

#1123 fix prebuilt error
  csrc/mmdeploy/apis/python/CMakeLists.txt
Labels: Bug:P0

#1131 [Fix] fix mmedit test picture
  tests/regression/mmedit.yml
Labels: Bug:P0

#1138 Expand rewrite scope for swin det
  mmdeploy/codebase/mmdet/models/backbones.py
Labels: bug
