Repository open-mmlab/mmdeploy, pull requests merged in 2023-08, with the labels that each got.

#2319 fix pytorch deepcopy trace error
  mmdeploy/pytorch/functions/__init__.py
  mmdeploy/pytorch/functions/copy.py
  tests/test_pytorch/test_pytorch_functions.py
Labels: bug

#2307 feat(demo): add time profile
  demo/csrc/cpp/classifier.cxx
  demo/csrc/cpp/detector.cxx
  demo/csrc/cpp/pose_detector.cxx
  demo/csrc/cpp/restorer.cxx
  demo/csrc/cpp/rotated_detector.cxx
  demo/csrc/cpp/segmentor.cxx
Labels: feature

#2321 the c++ code in get_started docs
  docs/en/get_started.md
  docs/zh_cn/get_started.md
Labels: documentation

#2320 [CodeCamp2023-553]翻译ort/trt后端编译中文文档
  docs/zh_cn/05-supported-backends/onnxruntime.md
  docs/zh_cn/05-supported-backends/tensorrt.md
Labels: documentation

#2356 [Fix] Fix random color for Palette
  demo/csrc/cpp/utils/palette.h
Labels: bug

#2339 fix(demo): add warmup for wrong profiling result
  demo/csrc/cpp/classifier.cxx
  demo/csrc/cpp/detector.cxx
  demo/csrc/cpp/pose_detector.cxx
  demo/csrc/cpp/restorer.cxx
  demo/csrc/cpp/rotated_detector.cxx
  demo/csrc/cpp/segmentor.cxx
  tools/scripts/build_ubuntu_x64_ncnn.py
Labels: bug

#2363 [Docs] Fix mmseg document
  docs/zh_cn/04-supported-codebases/mmseg.md
Labels: documentation

#2371 Update QR Code
  README_zh-CN.md
Labels: documentation

#2347 [Feature]: Support deployment of panoptic segmentation models
  .github/scripts/prepare_reg_test.py
  configs/mmdet/_base_/base_panoptic-seg_static.py
  configs/mmdet/panoptic-seg/panoptic-seg_maskformer_onnxruntime_dynamic.py
  configs/mmdet/panoptic-seg/panoptic-seg_maskformer_onnxruntime_static-800x1344.py
  configs/mmdet/panoptic-seg/panoptic-seg_maskformer_tensorrt_dynamic-320x512-1344x1344.py
  configs/mmdet/panoptic-seg/panoptic-seg_maskformer_tensorrt_static-800x1344.py
  configs/mmdet/panoptic-seg/panoptic-seg_panoptic-fpn_onnxruntime_dynamic.py
  configs/mmdet/panoptic-seg/panoptic-seg_panoptic-fpn_tensorrt_dynamic-352x512-1344x1344.py
  docs/en/04-supported-codebases/mmdet.md
  docs/zh_cn/04-supported-codebases/mmdet.md
  mmdeploy/apis/onnx/export.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  mmdeploy/codebase/mmdet/models/__init__.py
  mmdeploy/codebase/mmdet/models/detectors/__init__.py
  mmdeploy/codebase/mmdet/models/detectors/maskformer.py
  mmdeploy/codebase/mmdet/models/detectors/panoptic_two_stage_segmentor.py
  mmdeploy/codebase/mmdet/models/detectors/single_stage.py
  mmdeploy/codebase/mmdet/models/detectors/two_stage.py
  mmdeploy/codebase/mmdet/models/seg_heads/__init__.py
  mmdeploy/codebase/mmdet/models/seg_heads/base_semantic_head.py
  mmdeploy/mmcv/ops/multi_scale_deform_attn.py
  tests/regression/mmdet.yml
Labels: feature-wanted

#2364 fix urls in CI and readthedocs
  .github/scripts/test_onnx2ncnn.py
  .github/workflows/backend-ncnn.yml
  .github/workflows/backend-snpe.yml
  .github/workflows/build.yml
  .github/workflows/regression-test.yml
  .github/workflows/stale.yml
  .readthedocs.yml
  mmdeploy/apis/onnx/export.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  tests/test_apis/test_onnx_passes.py
Labels: CI

#2392 fix mmdet export for coreml backend
  docs/en/01-how-to-build/macos-arm64.md
  docs/en/05-supported-backends/coreml.md
  docs/zh_cn/01-how-to-build/macos-arm64.md
  docs/zh_cn/05-supported-backends/coreml.md
  mmdeploy/backend/coreml/ops.py
Labels: bug
