Repository open-mmlab/mmdeploy, pull requests merged in 2023-07, with the labels that each got.

#2229 add is_resize_mask cfg in inst seg
  csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp
  mmdeploy/codebase/mmdet/deploy/object_detection.py
Labels: enhancement

#2215 fix mmdeploy.version_info
  mmdeploy/__init__.py
Labels: enhancement

#2248 [Docs] Fix yolox-pose link
  docs/en/04-supported-codebases/mmpose.md
  docs/zh_cn/04-supported-codebases/mmpose.md
Labels: documentation

#2278 update rknn-toolkit2 version to 1.5
  csrc/mmdeploy/net/rknn/rknn_net.cpp
  docs/en/01-how-to-build/rockchip.md
  docs/zh_cn/01-how-to-build/rockchip.md
  mmdeploy/backend/rknn/onnx2rknn.py
Labels: enhancement

#2259 Update model-support-list
  configs/mmaction/video-recognition/video-recognition_torchscript.py
  docs/en/01-how-to-build/build_from_source.md
  docs/en/04-supported-codebases/mmaction2.md
  docs/en/04-supported-codebases/mmseg.md
  docs/zh_cn/01-how-to-build/build_from_source.md
  docs/zh_cn/04-supported-codebases/mmaction2.md
  docs/zh_cn/04-supported-codebases/mmseg.md
  tests/regression/mmaction.yml
  tests/regression/mmdet.yml
  tests/regression/mmseg.yml
Labels: feature

#2269 Support onnxruntime fp16
  .github/workflows/regression-test.yml
  configs/_base_/backends/onnxruntime-fp16.py
  configs/mmaction/video-recognition/video-recognition_onnxruntime-fp16_static.py
  configs/mmagic/super-resolution/super-resolution_onnxruntime-fp16_dynamic.py
  configs/mmdet/detection/detection_onnxruntime-fp16_dynamic.py
  configs/mmdet/instance-seg/instance-seg_onnxruntime-fp16_dynamic.py
  configs/mmdet3d/voxel-detection/voxel-detection_onnxruntime-fp16_dynamic.py
  configs/mmocr/text-detection/text-detection_onnxruntime-fp16_dynamic.py
  configs/mmocr/text-recognition/text-recognition_onnxruntime-fp16_dynamic.py
  configs/mmpose/pose-detection_onnxruntime-fp16_static.py
  configs/mmpose/pose-detection_simcc_onnxruntime-fp16_dynamic.py
  configs/mmpretrain/classification_onnxruntime-fp16_dynamic.py
  configs/mmrotate/rotated-detection_onnxruntime-fp16_dynamic.py
  configs/mmseg/segmentation_onnxruntime-fp16_dynamic.py
  docs/en/05-supported-backends/onnxruntime.md
  docs/en/05-supported-backends/openvino.md
  docs/zh_cn/05-supported-backends/onnxruntime.md
  docs/zh_cn/05-supported-backends/openvino.md
  mmdeploy/backend/onnxruntime/backend_manager.py
  mmdeploy/backend/onnxruntime/wrapper.py
  tests/regression/mmaction.yml
  tests/regression/mmagic.yml
  tests/regression/mmdet.yml
  tests/regression/mmdet3d.yml
  tests/regression/mmocr.yml
  tests/regression/mmpose.yml
  tests/regression/mmpretrain.yml
  tests/regression/mmrotate.yml
  tests/regression/mmseg.yml
Labels: feature

#2305 [Fix] Prevent RuntimeError in ONNX export with empty input in ONNXNMSRotatedOp
  mmdeploy/mmcv/ops/nms_rotated.py
Labels: bug
