Repository open-mmlab/mmdeploy, pull requests merged in 2023-03, with the labels that each got.

#1819 [Fix] Fix reduction fp16 exceed
  csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
Labels: Bug:P1

#1790 [Fix] Fix unit test in dev1.x
  docs/en/01-how-to-build/rockchip.md
  docs/zh_cn/01-how-to-build/rockchip.md
  mmdeploy/codebase/mmdet/models/dense_heads/detr_head.py
  mmdeploy/codebase/mmedit/deploy/super_resolution_model.py
  mmdeploy/mmcv/ops/nms_rotated.py
  tests/test_apis/test_torch2torchscript.py
  tests/test_codebase/test_mmaction/test_mmaction_model.py
  tests/test_codebase/test_mmcls/test_mmcls_models.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
  tests/test_codebase/test_mmedit/data/model.py
  tests/test_codebase/test_mmedit/test_super_resolution.py
  tests/test_codebase/test_mmedit/test_super_resolution_model.py
  tests/test_codebase/test_mmrotate/data/model.py
Labels: Bug:P1

#1833 [Fix] Fix clip on tensorrt 8.0
  mmdeploy/codebase/mmdet/deploy/utils.py
Labels: Bug:P1

#1793 [Enhancement] upgrade onnx to 1.13.0 to resolve security issue
  docs/en/get_started.md
  requirements/runtime.txt
Labels: improvement

#1855 [Fix] Add unified device guard
  csrc/mmdeploy/core/device.h
  csrc/mmdeploy/core/device_impl.cpp
  csrc/mmdeploy/core/device_impl.h
  csrc/mmdeploy/device/cpu/cpu_device.cpp
  csrc/mmdeploy/device/cpu/cpu_device.h
  csrc/mmdeploy/device/cuda/cuda_device.cpp
  csrc/mmdeploy/device/cuda/cuda_device.h
  csrc/mmdeploy/net/ort/ort_net.cpp
  csrc/mmdeploy/net/ort/ort_net.h
  csrc/mmdeploy/net/trt/trt_net.cpp
  csrc/mmdeploy/net/trt/trt_net.h
Labels: SDK

#1870 [Fix] Fix MobileOne deployment.
  mmdeploy/codebase/base/task.py
  tests/regression/mmcls.yml
Labels: Bug:P0

#1701 support mmrazor
  mmdeploy/apis/utils/utils.py
  mmdeploy/codebase/mmrazor/deploy/__init__.py
  mmdeploy/codebase/mmrazor/deploy/mmrazor.py
  mmdeploy/utils/config_utils.py
  mmdeploy/utils/constants.py
Labels: enhancement

#1851 [Enhancement] rewrite torch.cat for TensorRT when input is dynamic
  mmdeploy/pytorch/functions/__init__.py
  mmdeploy/pytorch/functions/cat.py
  tests/test_pytorch/test_pytorch_functions.py
Labels: enhancement

#1844 support multi_scale_deform_attn trt plugin
  csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn.cpp
  csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn.hpp
  csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.cu
  csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.cuh
  csrc/mmdeploy/backend_ops/tensorrt/multi_scale_deform_attn/trt_ms_deform_attn_kernel.hpp
  docs/en/06-custom-ops/tensorrt.md
  mmdeploy/backend/tensorrt/wrapper.py
  mmdeploy/mmcv/ops/__init__.py
  mmdeploy/mmcv/ops/multi_scale_deform_attn.py
  tests/test_ops/test_ops.py
Labels: enhancement

#1850 [Fix] Fix the warning method that calls the trt logger
  mmdeploy/backend/tensorrt/utils.py
Labels: Bug:P1

#1884 [Fix] Fix RTMDet-Ins head deploy
  mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_ins_head.py
Labels: Bug:P1

#1857 [Feature] Support RTMDet and RTMPose ncnn deployment
  configs/mmdet/detection/single-stage_ncnn-fp16_static-320x320.py
  configs/mmdet/detection/single-stage_ncnn_static-320x320.py
  configs/mmpose/pose-detection_simcc_ncnn-fp16_static-256x192.py
  csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/onnx2ncnn.cpp
  mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_head.py
  mmdeploy/codebase/mmpose/models/__init__.py
  mmdeploy/codebase/mmpose/models/utils/__init__.py
  mmdeploy/codebase/mmpose/models/utils/rtmcc_block.py
  mmdeploy/pytorch/functions/normalize.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
  tests/test_codebase/test_mmpose/test_mmpose_models.py
  tests/test_pytorch/test_pytorch_functions.py
Labels: dev-1.x, feature

#1842 [Fix] Fix ascend faster-rcnn
  configs/mmdet/detection/detection_ascend_static-800x1344.py
  mmdeploy/backend/ascend/wrapper.py
  mmdeploy/codebase/mmdet/deploy/utils.py
  mmdeploy/codebase/mmdet/models/roi_heads/standard_roi_head.py
  mmdeploy/mmcv/ops/nms.py
Labels: Bug:P1

#1867 [Enhancement] Support RTMDet-Ins
  csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp
  demo/python/object_detection.py
  mmdeploy/codebase/mmdet/deploy/object_detection.py
Labels: SDK

#1852 [Feature]: Add github prebuild workflow after new release.
  .github/workflows/prebuild.yml
  .pre-commit-config.yaml
  MANIFEST.in
  cmake/loader.cpp.in
  csrc/mmdeploy/apis/python/CMakeLists.txt
  csrc/mmdeploy/backend_ops/onnxruntime/CMakeLists.txt
  docker/prebuild/Dockerfile
  requirements/codebases.txt
  tools/package_tools/configs/linux_x64.yaml
  tools/package_tools/configs/windows_x64.yaml
  tools/package_tools/generate_build_config.py
  tools/package_tools/mmdeploy_builder.py
  tools/package_tools/packaging/MANIFEST.in
  tools/package_tools/packaging/mmdeploy_python/__init__.py
  tools/package_tools/packaging/mmdeploy_python/_win_dll_path.py
  tools/package_tools/packaging/setup.py
  tools/package_tools/scripts/linux/README.md
  tools/package_tools/scripts/linux/build_sdk.sh
  tools/package_tools/scripts/linux/install_opencv.sh
  tools/package_tools/scripts/linux/set_env.sh
  tools/package_tools/scripts/windows/README.md
  tools/package_tools/scripts/windows/build_sdk.ps1
  tools/package_tools/scripts/windows/install_opencv.ps1
  tools/package_tools/scripts/windows/set_env.ps1
  tools/package_tools/test/test_sdk.ps1
  tools/package_tools/test/test_sdk.sh
  tools/package_tools/test/test_sdk_python.ps1
  tools/package_tools/test/test_sdk_python.sh
Labels: enhancement

#1944 docs(project): openvino upgrade to 2022.3.0
  README.md
  README_zh-CN.md
  docs/en/01-how-to-build/linux-x86_64.md
  docs/en/05-supported-backends/openvino.md
  docs/zh_cn/01-how-to-build/linux-x86_64.md
  docs/zh_cn/05-supported-backends/openvino.md
  requirements/optional.txt
Labels: documentation
