Repository open-mmlab/mmdeploy, pull requests merged in 2023-09, with the labels that each got.

#2343 [Fix]: fix rtmdet-inst sdk
  csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp
  demo/csrc/c/object_detection.cpp
  demo/csrc/cpp/utils/visualize.h
  demo/python/object_detection.py
  docs/en/07-developer-guide/regression_test.md
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_ins_head.py
  mmdeploy/mmcv/ops/nms.py
  tests/regression/mmdet.yml
Labels: bug

#2256 Mobilenet V3 to ONNX support
  docs/en/03-benchmark/supported_models.md
  docs/en/04-supported-codebases/mmpretrain.md
  docs/zh_cn/03-benchmark/supported_models.md
  docs/zh_cn/04-supported-codebases/mmpretrain.md
  mmdeploy/codebase/mmpretrain/deploy/classification.py
  tests/regression/mmpretrain.yml
Labels: feature

#2378 docs(build): add more example
  .github/workflows/lint.yml
  docs/en/01-how-to-build/linux-x86_64.md
  docs/zh_cn/01-how-to-build/linux-x86_64.md
Labels: documentation

#2292 refine gemm in ort mdcn
  csrc/mmdeploy/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp
Labels: enhancement

#2406 Fix ONNX Runtime Op memory leak
  csrc/mmdeploy/backend_ops/onnxruntime/modulated_deform_conv/modulated_deform_conv.cpp
  csrc/mmdeploy/backend_ops/onnxruntime/nms_rotated/nms_rotated.cpp
Labels: bug

#2411 Fix sdk error for multi-gpu execution
  csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp
  csrc/mmdeploy/preprocess/transform/compose.cpp
Labels: bug

#2418 Rename MMEdit to MMagic
  mmdeploy/codebase/mmagic/__init__.py
  mmdeploy/codebase/mmagic/deploy/__init__.py
  mmdeploy/codebase/mmagic/deploy/mmagic.py
  mmdeploy/codebase/mmagic/deploy/super_resolution.py
  tools/elena/extract_transform.py
Labels: enhancement

#2410 Support dino from mmdet
  docs/en/04-supported-codebases/mmdet.md
  docs/zh_cn/04-supported-codebases/mmdet.md
  mmdeploy/codebase/mmdet/models/dense_heads/detr_head.py
  mmdeploy/codebase/mmdet/models/detectors/__init__.py
  mmdeploy/codebase/mmdet/models/detectors/base_detr.py
  mmdeploy/utils/config_utils.py
  tests/regression/mmdet.yml
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: planned feature

#2426 fix img load for super-resolution in sdk
  csrc/mmdeploy/preprocess/transform/load.cpp
Labels: bug

#2428 fix roi align symbolic function in onnx opset>=16
  mmdeploy/mmcv/ops/roi_align.py
Labels: bug

#2425 fix torch2onnx for mmdet3d
  .github/md-link-config.json
  .github/workflows/regression-test.yml
  configs/mmdet/detection/single-stage_ncnn_static-640x640.py
  docs/en/04-supported-codebases/mmdet3d.md
  docs/zh_cn/04-supported-codebases/mmdet3d.md
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/codebase/mmdet3d/deploy/mono_detection.py
  mmdeploy/codebase/mmdet3d/models/base.py
  mmdeploy/codebase/mmdet3d/models/mvx_two_stage.py
  mmdeploy/codebase/mmdet3d/models/single_stage_mono3d.py
  tests/regression/mmdet.yml
  tests/test_codebase/test_mmdet3d/test_mmdet3d_models.py
Labels: bug

#2453 Fix conversion with rtmdet-inst, vit, conformer
  mmdeploy/mmcv/ops/nms.py
  mmdeploy/pytorch/functions/multi_head_attention_forward.py
Labels: bug

#2449 export get_simcc_maximum for simcc
  .github/workflows/docker.yml
  .github/workflows/publish.yml
  configs/mmpose/pose-detection_simcc_onnxruntime_dynamic.py
  csrc/mmdeploy/codebase/mmpose/simcc_label.cpp
  mmdeploy/codebase/mmpose/codecs/__init__.py
  mmdeploy/codebase/mmpose/codecs/post_processing.py
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
  mmdeploy/codebase/mmpose/deploy/pose_detection_model.py
  mmdeploy/codebase/mmpose/models/heads/__init__.py
  mmdeploy/codebase/mmpose/models/heads/simcc_head.py
Labels: enhancement
