Repository open-mmlab/mmdeploy, pull requests merged in 2023-10, with the labels that each got.

#2476 CodeCamp2023-670
  docs/en/01-how-to-build/windows.md
  docs/zh_cn/01-how-to-build/windows.md
Labels: documentation

#2469 CodeCamp2023-555
  csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp
  mmdeploy/codebase/mmdet/deploy/object_detection.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  mmdeploy/codebase/mmdet/models/dense_heads/__init__.py
  mmdeploy/codebase/mmdet/models/dense_heads/condinst_head.py
  mmdeploy/codebase/mmdet/models/detectors/single_stage_instance_seg.py
  mmdeploy/pytorch/functions/repeat.py
  tests/regression/mmdet.yml
Labels: feature

#2481 add condinst ut & update docs
  docs/en/04-supported-codebases/mmdet.md
  docs/zh_cn/04-supported-codebases/mmdet.md
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: Unittest

#2438 support htc
  docs/en/04-supported-codebases/mmdet.md
  docs/zh_cn/04-supported-codebases/mmdet.md
  mmdeploy/codebase/mmdet/models/roi_heads/__init__.py
  mmdeploy/codebase/mmdet/models/roi_heads/cascade_roi_head.py
  mmdeploy/codebase/mmdet/models/roi_heads/htc_roi_head.py
  tests/regression/mmdet.yml
Labels: feature

#2466 [Fix] fix the onnx exportation for yoloxpose in mmpose
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
  mmdeploy/codebase/mmpose/deploy/pose_detection_model.py
  mmdeploy/codebase/mmpose/models/heads/yolox_pose_head.py
  tests/regression/mmpose.yml
  tests/test_codebase/test_mmpose/utils.py
Labels: enhancement

#2497 Roman duris/fix jetson wheel platform
  tools/package_tools/generate_build_config.py
Labels: enhancement, Jetson
