Repository open-mmlab/mmdeploy, pull requests merged in 2023-12, with the labels that each got.

#2597 [Feature] Support ONNX and TensorRT exportation of RTMO models
  configs/mmpose/pose-detection_rtmo_onnxruntime_dynamic.py
  configs/mmpose/pose-detection_rtmo_tensorrt-fp16_dynamic-640x640.py
  docs/en/04-supported-codebases/mmpose.md
  docs/zh_cn/04-supported-codebases/mmpose.md
  mmdeploy/codebase/base/task.py
  mmdeploy/codebase/mmpose/models/heads/__init__.py
  mmdeploy/codebase/mmpose/models/heads/rtmo_head.py
  tests/regression/mmpose.yml
Labels: feature

#2581 Fix wrong size of mask in RTMDet-Ins post-processing
  csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
Labels: bug

#2609 fix ci
  .github/scripts/linux/test_full_pipeline.sh
  .github/scripts/prepare_reg_test.py
  .github/scripts/windows/test_full_pipeline.ps1
  .github/workflows/build.yml
  .github/workflows/regression-test.yml
  docs/en/01-how-to-build/rockchip.md
  docs/zh_cn/01-how-to-build/rockchip.md
  mmdeploy/mmcv/ops/nms.py
  requirements/codebases.txt
  tests/regression/mmdet.yml
  tests/regression/mmocr.yml
  tests/regression/mmseg.yml
Labels: CI
