Repository open-mmlab/mmdeploy, pull requests merged in 2023-05, with the labels that each got.

#1997 [Fix]: fix mmseg exportation for out_channels=1
  .github/workflows/build.yml
  .github/workflows/quantize.yml
  mmdeploy/codebase/mmseg/deploy/segmentation.py
  mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py
  requirements/codebases.txt
  requirements/optional.txt
Labels: bug

#2054 【Doc】Update mmdet.md en/cn
  docs/en/04-supported-codebases/mmdet.md
  docs/zh_cn/04-supported-codebases/mmdet.md
Labels: documentation

#2018 [Fix] Fix dataloader for ncnn quantization
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
  tools/onnx2ncnn_quant_table.py
Labels: bug

#2058 fix ci
  .github/scripts/quantize_to_ncnn.py
  .github/workflows/backend-ncnn.yml
  .github/workflows/build.yml
  .github/workflows/quantize.yml
  .github/workflows/stale.yml
Labels: CI

#2070 [Fix]: limit urllib3 for readthedocs
  requirements/readthedocs.txt
Labels: documentation

#2056 fix with_argmax for mmseg
  mmdeploy/codebase/mmseg/deploy/segmentation.py
Labels: bug

#2063 [Fix] swap width and height in Resize and Pad according to upstream codebases
  csrc/mmdeploy/preprocess/transform/pad.cpp
  csrc/mmdeploy/preprocess/transform/resize.cpp
  tests/test_csrc/preprocess/test_pad.cpp
  tests/test_csrc/preprocess/test_resize.cpp
Labels: Bug:P0

#2071 [Enhancement]: Support opset_version 13
  docker/Base/Dockerfile
  mmdeploy/apis/onnx/optimizer.py
  mmdeploy/apis/onnx/passes/optimize_onnx.py
  mmdeploy/codebase/mmdet/models/task_modules/prior_generators/anchor.py
  mmdeploy/codebase/mmdet3d/deploy/voxel_detection.py
  tests/regression/mmseg.yml
  tools/regression_test.py
Labels: enhancement

#2064 [Feature] add attention convertor
  csrc/mmdeploy/codebase/mmocr/attention_convertor.cpp
  mmdeploy/codebase/mmocr/deploy/text_recognition.py
Labels: feature

#2020 Update Github Badge for Workflow
  .github/workflows/backend-ncnn.yml
  .github/workflows/backend-pplnn.yml
  .github/workflows/build.yml
  README.md
  README_zh-CN.md
Labels: documentation

#2092 [Enhancement] refine mmagic SDKEnd2EndModel forward
  mmdeploy/codebase/mmagic/deploy/super_resolution_model.py
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
Labels: enhancement

#2081 CI: Add regression test workflow
  .github/scripts/gen_reg_summary.py
  .github/scripts/linux/build.sh
  .github/scripts/prepare_reg_test.py
  .github/workflows/build.yml
  .github/workflows/prebuild.yml
  .github/workflows/regression-test.yml
  csrc/mmdeploy/backend_ops/ncnn/onnx2ncnn/CMakeLists.txt
  csrc/mmdeploy/backend_ops/torchscript/ops/CMakeLists.txt
  csrc/mmdeploy/codebase/CMakeLists.txt
  docker/Release/Dockerfile
  docs/en/04-supported-codebases/mmpose.md
  docs/zh_cn/04-supported-codebases/mmpose.md
  mmdeploy/backend/ncnn/__init__.py
  mmdeploy/backend/sdk/export_info.py
  mmdeploy/codebase/mmseg/deploy/segmentation.py
  tools/regression_test.py
Labels: CI

#1872 add deform conv v3 plugin
  csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3.cpp
  csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3.hpp
  csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3_kernel.cu
  csrc/mmdeploy/backend_ops/tensorrt/modulated_deform_conv_v3/trt_deform_conv_v3_kernel.hpp
  docs/en/06-custom-ops/tensorrt.md
  docs/zh_cn/06-custom-ops/tensorrt.md
Labels: feature

#2094 bump version to v1.1.0
  CMakeLists.txt
  csrc/mmdeploy/apis/csharp/README.md
  demo/csharp/image_classification/image_classification.csproj
  demo/csharp/image_restorer/image_restorer.csproj
  demo/csharp/image_segmentation/image_segmentation.csproj
  demo/csharp/object_detection/object_detection.csproj
  demo/csharp/ocr_detection/ocr_detection.csproj
  demo/csharp/ocr_recognition/ocr_recognition.csproj
  demo/csharp/pose_detection/pose_detection.csproj
  docs/en/02-how-to-run/prebuilt_package_windows.md
  docs/en/get_started.md
  docs/zh_cn/02-how-to-run/prebuilt_package_windows.md
  docs/zh_cn/get_started.md
  mmdeploy/version.py
  tools/package_tools/packaging/mmdeploy_runtime/version.py
Labels: documentation

#2105 fix function rewriter
  mmdeploy/core/rewriters/function_rewriter.py
Labels: Bug:P0

#2107 fix prebuild
  .github/workflows/prebuild.yml
  tools/package_tools/mmdeploy_builder.py
Labels: CI

#2112 fix prebuild uploading
  .github/workflows/prebuild.yml
  .github/workflows/publish.yml
  tools/package_tools/test/test_sdk.ps1
  tools/package_tools/test/test_sdk_python.ps1
  tools/package_tools/test/test_sdk_python.sh
Labels: CI

#2120 docs(project): deploee introduction
  README.md
  README_zh-CN.md
Labels: documentation

#2122 [Fix] fix mmseg output sync
  csrc/mmdeploy/codebase/mmseg/segment.cpp
Labels: bug

#2114 Update docs
  csrc/mmdeploy/codebase/mmocr/pixel_group.cpp
  docs/en/02-how-to-run/convert_model.md
  docs/en/02-how-to-run/write_config.md
  docs/en/03-benchmark/benchmark.md
  docs/en/03-benchmark/benchmark_edge.md
  docs/en/03-benchmark/benchmark_tvm.md
  docs/en/03-benchmark/quantization.md
  docs/en/03-benchmark/supported_models.md
  docs/en/04-supported-codebases/mmdet3d.md
  docs/en/04-supported-codebases/mmocr.md
  docs/en/04-supported-codebases/mmpose.md
  docs/en/04-supported-codebases/mmpretrain.md
  docs/en/04-supported-codebases/mmseg.md
  docs/zh_cn/01-how-to-build/android.md
  docs/zh_cn/01-how-to-build/build_from_source.md
  docs/zh_cn/01-how-to-build/jetsons.md
  docs/zh_cn/02-how-to-run/convert_model.md
  docs/zh_cn/02-how-to-run/prebuilt_package_windows.md
  docs/zh_cn/02-how-to-run/write_config.md
  docs/zh_cn/03-benchmark/benchmark.md
  docs/zh_cn/03-benchmark/benchmark_edge.md
  docs/zh_cn/03-benchmark/benchmark_tvm.md
  docs/zh_cn/03-benchmark/quantization.md
  docs/zh_cn/03-benchmark/supported_models.md
  docs/zh_cn/04-supported-codebases/mmdet3d.md
  docs/zh_cn/04-supported-codebases/mmocr.md
  docs/zh_cn/04-supported-codebases/mmpose.md
  docs/zh_cn/04-supported-codebases/mmrotate.md
  docs/zh_cn/04-supported-codebases/mmseg.md
  docs/zh_cn/tutorial/07_write_a_plugin.md
  resources/tutorial/IPluginV2DynamicExt.svg
  resources/tutorial/srcnn.svg
Labels: documentation

#2134 Fix readthedocs
  .github/workflows/quantize.yml
  docs/zh_cn/tutorial/07_write_a_plugin.md
  requirements/readthedocs.txt
  resources/tutorial/IPluginV2DynamicExt.svg
  resources/tutorial/srcnn.svg
Labels: documentation

#2118 support mscv statically linked CRT
  CMakeLists.txt
  cmake/cuda.cmake
  csrc/mmdeploy/backend_ops/CMakeLists.txt
Labels: enhancement
