Repository open-mmlab/mmdeploy, pull requests merged in 2023-04, with the labels that each got.

#1947 Update get_started.md
  .github/workflows/prebuild.yml
  docs/en/02-how-to-run/prebuilt_package_windows.md
  docs/en/get_started.md
  docs/zh_cn/02-how-to-run/prebuilt_package_windows.md
  docs/zh_cn/get_started.md
  tools/package_tools/generate_build_config.py
  tools/package_tools/scripts/linux/README.md
  tools/package_tools/scripts/windows/README.md
  tools/package_tools/test/test_sdk.sh
Labels: documentation

#1789 [Doc] update SAR status
  docs/en/04-supported-codebases/mmocr.md
  docs/zh_cn/04-supported-codebases/mmocr.md
  mmdeploy/codebase/mmocr/models/text_recognition/sar_decoder.py
  mmdeploy/codebase/mmocr/models/text_recognition/sar_encoder.py
  tests/regression/mmocr.yml
Labels: documentation

#1986 Generate supported-backends markdown table
  docs/en/02-how-to-run/useful_tools.md
  docs/zh_cn/02-how-to-run/useful_tools.md
  docs/zh_cn/tutorial/03_pytorch2onnx.md
  docs/zh_cn/tutorial/04_onnx_custom_op.md
  requirements/codebases.txt
  tests/regression/mmaction.yml
  tests/regression/mmcls.yml
  tests/regression/mmdet.yml
  tests/regression/mmdet3d.yml
  tests/regression/mmedit.yml
  tests/regression/mmocr.yml
  tests/regression/mmpose.yml
  tests/regression/mmrotate.yml
  tests/regression/mmseg.yml
  tools/generate_md_table.py
Labels: documentation

#1978 [Docs] Update mmcls doc
  docs/en/04-supported-codebases/mmcls.md
  docs/zh_cn/04-supported-codebases/mmcls.md
Labels: documentation

#1980 Fix rknn and aarch64 build ci
  .github/workflows/backend-rknn.yml
  .github/workflows/build.yml
  tools/scripts/ubuntu_cross_build_aarch64.sh
  tools/scripts/ubuntu_cross_build_rknn.sh
Labels: bug, CI

#2022 [Docs]update mmseg docs
  docs/en/04-supported-codebases/mmseg.md
  docs/zh_cn/04-supported-codebases/mmseg.md
Labels: documentation

#1521 CodeCamp #106: Support SOLOv2 deployment with OpenVINO
  docs/en/03-benchmark/benchmark.md
  docs/en/03-benchmark/supported_models.md
  docs/en/04-supported-codebases/mmdet.md
  docs/zh_cn/03-benchmark/benchmark.md
  docs/zh_cn/03-benchmark/supported_models.md
  docs/zh_cn/04-supported-codebases/mmdet.md
  mmdeploy/codebase/mmdet/deploy/object_detection_model.py
  mmdeploy/codebase/mmdet/models/dense_heads/__init__.py
  mmdeploy/codebase/mmdet/models/dense_heads/solo_head.py
  mmdeploy/codebase/mmdet/models/dense_heads/solov2_head.py
  mmdeploy/pytorch/functions/linspace.py
  mmdeploy/utils/test.py
  tests/regression/mmdet.yml
  tests/test_codebase/test_mmdet/test_mmdet_models.py
Labels: feature

#2010 [Feature] Support quantization deployment
  configs/_base_/backends/tensorrt-int8-explicit.py
  configs/mmcls/classification_tensorrt-int8-explicit_dynamic-224x224-224x224.py
  configs/mmdet/_base_/base_tensorrt-int8-explicit_dynamic-320x320-1344x1344.py
  configs/mmdet/detection/detection_tensorrt-int8-explicit_dynamic-320x320-1344x1344.py
  mmdeploy/apis/onnx/export.py
  mmdeploy/backend/tensorrt/onnx2tensorrt.py
  mmdeploy/backend/tensorrt/utils.py
  mmdeploy/codebase/mmrazor/deploy/mmrazor.py
  mmdeploy/pytorch/functions/cat.py
  mmdeploy/pytorch/functions/interpolate.py
  requirements/codebases.txt
Labels: feature

#2031 Update Repo List in README
  README.md
  README_zh-CN.md
Labels: documentation

#2038 Add with argmax
  configs/mmseg/segmentation_rknn-fp16_static-320x320.py
  configs/mmseg/segmentation_rknn-int8_static-320x320.py
  configs/mmseg/segmentation_static.py
  docs/en/04-supported-codebases/mmseg.md
  docs/zh_cn/04-supported-codebases/mmseg.md
  mmdeploy/codebase/mmseg/deploy/segmentation.py
  mmdeploy/codebase/mmseg/deploy/segmentation_model.py
  mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py
Labels: improvement

#1994 Update build_from_source.md
  docs/en/01-how-to-build/build_from_source.md
  docs/zh_cn/01-how-to-build/build_from_source.md
Labels: documentation

#2027 [Enhancement] Load openvino model from memory
  csrc/mmdeploy/net/openvino/openvino_net.cpp
  docker/CPU/Dockerfile
Labels: enhancement
