Repository open-mmlab/mmdeploy, pull requests merged in 2023-06, with the labels that each got.

#2130 fix uploading assets
  .github/workflows/publish.yml
Labels: CI

#2108 Fit for MMPretrain EfficientFormer
  docs/en/03-benchmark/benchmark.md
  docs/en/04-supported-codebases/mmpretrain.md
  docs/zh_cn/03-benchmark/benchmark.md
  docs/zh_cn/04-supported-codebases/mmpretrain.md
  mmdeploy/codebase/mmpretrain/deploy/classification.py
  tests/regression/mmpretrain.yml
Labels: feature

#2154 Update build_ubuntu_x64_ncnn.py
  tools/scripts/build_ubuntu_x64_ncnn.py
Labels: enhancement

#2142 update document for docker installation
  .github/workflows/docker.yml
  docker/Release/Dockerfile
  docs/en/01-how-to-build/build_from_docker.md
  docs/zh_cn/01-how-to-build/build_from_docker.md
  requirements/backends.txt
Labels: documentation, docker

#2153 [ADD] pplcv area interpolation
  csrc/mmdeploy/operation/cuda/resize.cpp
  tests/test_csrc/preprocess/test_resize.cpp
Labels: enhancement

#2139 [Fix] fix satrn onnxruntime batch inference
  mmdeploy/codebase/mmocr/models/text_recognition/__init__.py
  mmdeploy/codebase/mmocr/models/text_recognition/nrtr_decoder.py
  mmdeploy/codebase/mmocr/models/text_recognition/satrn_encoder.py
  tests/test_codebase/test_mmocr/test_mmocr_models.py
Labels: bug

#2175 Update readme intro image and docs
  .github/workflows/build.yml
  .github/workflows/docker.yml
  configs/mmpose/pose-detection_simcc_openvino_static-256x192.py
  docs/en/03-benchmark/supported_models.md
  docs/en/04-supported-codebases/mmdet.md
  docs/en/04-supported-codebases/mmpose.md
  docs/en/04-supported-codebases/mmpretrain.md
  docs/en/05-supported-backends/onnxruntime.md
  docs/en/05-supported-backends/openvino.md
  docs/zh_cn/03-benchmark/supported_models.md
  docs/zh_cn/04-supported-codebases/mmdet.md
  docs/zh_cn/04-supported-codebases/mmpose.md
  docs/zh_cn/04-supported-codebases/mmpretrain.md
  docs/zh_cn/05-supported-backends/onnxruntime.md
  docs/zh_cn/05-supported-backends/openvino.md
  resources/introduction.png
  tests/test_apis/test_onnx_passes.py
Labels: documentation

#2157 Add Sdk Doxygen document.
  .gitignore
  docs/cppapi/Doxyfile
  docs/en/conf.py
  docs/en/index.rst
  docs/en/sdk_usage/c/classifier.rst
  docs/en/sdk_usage/c/common.rst
  docs/en/sdk_usage/c/detector.rst
  docs/en/sdk_usage/c/executor.rst
  docs/en/sdk_usage/c/model.rst
  docs/en/sdk_usage/c/pipeline.rst
  docs/en/sdk_usage/c/pose_detector.rst
  docs/en/sdk_usage/c/pose_tracker.rst
  docs/en/sdk_usage/c/rotated_detector.rst
  docs/en/sdk_usage/c/segmentor.rst
  docs/en/sdk_usage/c/text_detector.rst
  docs/en/sdk_usage/c/text_recognizer.rst
  docs/en/sdk_usage/c/video_recognizer.rst
  docs/en/sdk_usage/c_api.rst
  docs/en/sdk_usage/index.rst
  docs/en/sdk_usage/quick_start.md
  docs/zh_cn/conf.py
  docs/zh_cn/index.rst
  docs/zh_cn/sdk_usage/c/classifier.rst
  docs/zh_cn/sdk_usage/c/common.rst
  docs/zh_cn/sdk_usage/c/detector.rst
  docs/zh_cn/sdk_usage/c/executor.rst
  docs/zh_cn/sdk_usage/c/model.rst
  docs/zh_cn/sdk_usage/c/pipeline.rst
  docs/zh_cn/sdk_usage/c/pose_detector.rst
  docs/zh_cn/sdk_usage/c/pose_tracker.rst
  docs/zh_cn/sdk_usage/c/rotated_detector.rst
  docs/zh_cn/sdk_usage/c/segmentor.rst
  docs/zh_cn/sdk_usage/c/text_detector.rst
  docs/zh_cn/sdk_usage/c/text_recognizer.rst
  docs/zh_cn/sdk_usage/c/video_recognizer.rst
  docs/zh_cn/sdk_usage/c_api.rst
  docs/zh_cn/sdk_usage/index.rst
  docs/zh_cn/sdk_usage/quick_start.md
  requirements/readthedocs.txt
Labels: documentation

#2186 Add coco-wholebody-hand skeleton
  demo/csrc/cpp/pose_tracker.cxx
  demo/csrc/cpp/utils/skeleton.h
Labels: enhancement

#2179 fix mmseg out_channels=1
  configs/mmocr/text-detection/text-detection_ncnn-int8_static.py
  docs/en/05-supported-backends/onnxruntime.md
  mmdeploy/codebase/mmseg/models/segmentors/base.py
  mmdeploy/codebase/mmseg/models/segmentors/cascade_encoder_decoder.py
  mmdeploy/codebase/mmseg/models/segmentors/encoder_decoder.py
  tests/test_codebase/test_mmseg/test_mmseg_models.py
  tests/test_codebase/test_mmseg/utils.py
Labels: bug

#2095 [Fix] fix mmdeploy android library size
  CMakeLists.txt
  csrc/mmdeploy/codebase/mmcls/CMakeLists.txt
  csrc/mmdeploy/codebase/mmdet/CMakeLists.txt
  csrc/mmdeploy/codebase/mmedit/CMakeLists.txt
  csrc/mmdeploy/codebase/mmpose/CMakeLists.txt
  docs/en/01-how-to-build/android.md
  docs/zh_cn/01-how-to-build/android.md
Labels: enhancement

#2189 add sdk profiler docs
  docs/en/sdk_usage/index.rst
  docs/en/sdk_usage/profiler.md
  docs/zh_cn/sdk_usage/index.rst
  docs/zh_cn/sdk_usage/profiler.md
Labels: documentation

#2185 [Feature] Enable read zip model in prebuild package.
  cmake/MMDeploy.cmake
  csrc/mmdeploy/apis/c/CMakeLists.txt
  csrc/mmdeploy/backend_ops/onnxruntime/CMakeLists.txt
  csrc/mmdeploy/model/CMakeLists.txt
  tools/package_tools/generate_build_config.py
Labels: feature

#2210 Fix torch2onnx for pointpillars with multi-level outputs
  configs/mmdet3d/voxel-detection/voxel-detection_static.py
  mmdeploy/codebase/mmdet3d/deploy/voxel_detection_model.py
  mmdeploy/codebase/mmdet3d/models/mvx_two_stage.py
Labels: bug

#2209 [Fix] Fix text recog task postprocess
  csrc/mmdeploy/codebase/mmocr/attention_convertor.cpp
  csrc/mmdeploy/codebase/mmocr/base_convertor.cpp
  csrc/mmdeploy/codebase/mmocr/base_convertor.h
  csrc/mmdeploy/codebase/mmocr/crnn.cpp
  mmdeploy/codebase/mmocr/deploy/text_recognition.py
Labels: bug

#2187 Fix some ut
  .github/workflows/build.yml
  mmdeploy/codebase/mmpretrain/models/backbones/__init__.py
  mmdeploy/codebase/mmpretrain/models/backbones/vision_transformer.py
  tests/test_apis/test_onnx2openvino.py
  tests/test_apis/test_onnx2tensorrt.py
  tests/test_codebase/test_mmocr/test_mmocr_models.py
  tests/test_codebase/test_mmpretrain/test_mmpretrain_models.py
  tests/test_ops/test_ops.py
  tests/test_ops/utils.py
Labels: Unittest

#2184 Support YoloX-Pose
  .github/workflows/build.yml
  configs/mmpose/pose-detection_yolox-pose_onnxruntime_dynamic.py
  configs/mmpose/pose-detection_yolox-pose_openvino_dynamic-640x640.py
  configs/mmpose/pose-detection_yolox-pose_tensorrt_dynamic-640x640.py
  csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/gatherNMSOutputs.cu
  docs/en/04-supported-codebases/mmpose.md
  docs/zh_cn/04-supported-codebases/mmpose.md
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
  mmdeploy/codebase/mmpose/deploy/pose_detection_model.py
  mmdeploy/codebase/mmpose/models/heads/__init__.py
  mmdeploy/codebase/mmpose/models/heads/yolox_pose_head.py
  mmdeploy/mmcv/ops/nms.py
  mmdeploy/utils/constants.py
  tests/test_codebase/test_mmpose/test_mmpose_models.py
  tests/test_codebase/test_mmpose/utils.py
Labels: feature

#2223 bump version to v1.2.0
  CMakeLists.txt
  csrc/mmdeploy/apis/csharp/README.md
  demo/csharp/image_classification/image_classification.csproj
  demo/csharp/image_restorer/image_restorer.csproj
  demo/csharp/image_segmentation/image_segmentation.csproj
  demo/csharp/object_detection/object_detection.csproj
  demo/csharp/ocr_detection/ocr_detection.csproj
  demo/csharp/ocr_recognition/ocr_recognition.csproj
  demo/csharp/pose_detection/pose_detection.csproj
  docs/en/01-how-to-build/build_from_docker.md
  docs/en/02-how-to-run/prebuilt_package_windows.md
  docs/en/get_started.md
  docs/zh_cn/01-how-to-build/build_from_docker.md
  docs/zh_cn/02-how-to-run/prebuilt_package_windows.md
  docs/zh_cn/get_started.md
  mmdeploy/version.py
  tools/package_tools/packaging/mmdeploy_runtime/version.py
Labels: documentation
