Repository open-mmlab/mmdeploy, pull requests merged in 2023-01, with the labels that each got.

#1603 Cherry-pick #1439 to fix 'topk' on different devices for onnxruntime-gpu inference
  mmdeploy/pytorch/functions/topk.py
Labels: Bug:P0, dev-1.x

#1620 [Doc] Fix Android build doc on master branch
  docs/en/01-how-to-build/android.md
  docs/zh_cn/01-how-to-build/android.md
Labels: documentation

#1600 [Fix] fix no test_step error in TorchWrapper
  tools/profiler.py
Labels: bug, dev-1.x

#1589 [Improvement] Support auto release note
  .github/release.yml
Labels: improvement

#1621 [Doc] update build doc for jetsons
  .circleci/config.yml
  docs/en/01-how-to-build/jetsons.md
  docs/zh_cn/01-how-to-build/jetsons.md
Labels: documentation

#1611 [Fix]: fix numba numpy version not compatiable in circileci
  .circleci/config.yml
  .circleci/test.yml
  tests/test_codebase/test_mmcls/data/model.py
  tests/test_codebase/test_mmcls/test_classification_model.py
Labels: CI

#1641 [Fix] Fix visualize api bug
  mmdeploy/apis/visualize.py
Labels: Bug:P0

#1631 [Fix] Substitute SyncBN with BN for mmpose
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
Labels: Bug:P0, dev-1.x

#1630 [Fix] fix headless device visualize
  mmdeploy/apis/visualize.py
  mmdeploy/codebase/base/task.py
Labels: Bug:P2

#1658 Fix coreml
  configs/mmcls/classification_coreml_static-384x384.py
  configs/mmdet/detection/detection_coreml_static-608x608.py
  configs/mmocr/text-recognition/text-recognition_coreml_dynamic-32x32-32x640.py
  mmdeploy/backend/coreml/backend_manager.py
  mmdeploy/backend/coreml/torchscript2coreml.py
  mmdeploy/codebase/mmdet/models/dense_heads/base_dense_head.py
  mmdeploy/pytorch/functions/topk.py
  tests/test_backend/test_wrapper.py
Labels: Bug:P0

#1666 [Fix] Fix several bugs in the preprocessing of single channel images
  csrc/mmdeploy/operation/cuda/cvtcolor.cpp
  csrc/mmdeploy/preprocess/transform/load.cpp
Labels: Bug:P0, SDK

#1593 [Improvement] suppress onnx optimizer warning
  csrc/mmdeploy/backend_ops/torchscript/optimizer/ir/subgraph_matcher.cpp
  csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/common_subgraph_elimination.cpp
  csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/fuse_select_assign.cpp
  csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/merge_shape_concate.cpp
  csrc/mmdeploy/backend_ops/torchscript/optimizer/passes/onnx/onnx_peephole.cpp
Labels: improvement

#1663 [Feature] Pose tracker C/C++/Python API&demos
  csrc/mmdeploy/apis/c/CMakeLists.txt
  csrc/mmdeploy/apis/c/mmdeploy/classifier.cpp
  csrc/mmdeploy/apis/c/mmdeploy/classifier.h
  csrc/mmdeploy/apis/c/mmdeploy/common.cpp
  csrc/mmdeploy/apis/c/mmdeploy/common_internal.h
  csrc/mmdeploy/apis/c/mmdeploy/detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/detector.h
  csrc/mmdeploy/apis/c/mmdeploy/executor.cpp
  csrc/mmdeploy/apis/c/mmdeploy/executor.h
  csrc/mmdeploy/apis/c/mmdeploy/executor_internal.h
  csrc/mmdeploy/apis/c/mmdeploy/model.cpp
  csrc/mmdeploy/apis/c/mmdeploy/model.h
  csrc/mmdeploy/apis/c/mmdeploy/pipeline.cpp
  csrc/mmdeploy/apis/c/mmdeploy/pipeline.h
  csrc/mmdeploy/apis/c/mmdeploy/pose_detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/pose_detector.h
  csrc/mmdeploy/apis/c/mmdeploy/pose_tracker.cpp
  csrc/mmdeploy/apis/c/mmdeploy/pose_tracker.h
  csrc/mmdeploy/apis/c/mmdeploy/restorer.cpp
  csrc/mmdeploy/apis/c/mmdeploy/restorer.h
  csrc/mmdeploy/apis/c/mmdeploy/rotated_detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/rotated_detector.h
  csrc/mmdeploy/apis/c/mmdeploy/segmentor.cpp
  csrc/mmdeploy/apis/c/mmdeploy/segmentor.h
  csrc/mmdeploy/apis/c/mmdeploy/text_detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/text_detector.h
  csrc/mmdeploy/apis/c/mmdeploy/text_recognizer.cpp
  csrc/mmdeploy/apis/c/mmdeploy/text_recognizer.h
  csrc/mmdeploy/apis/c/mmdeploy/video_recognizer.cpp
  csrc/mmdeploy/apis/c/mmdeploy/video_recognizer.h
  csrc/mmdeploy/apis/cxx/mmdeploy/common.hpp
  csrc/mmdeploy/apis/cxx/mmdeploy/pose_tracker.hpp
  csrc/mmdeploy/apis/python/pose_tracker.cpp
  csrc/mmdeploy/codebase/mmpose/CMakeLists.txt
  csrc/mmdeploy/codebase/mmpose/pose_tracker/common.h
  csrc/mmdeploy/codebase/mmpose/pose_tracker/pipeline.cpp
  csrc/mmdeploy/codebase/mmpose/pose_tracker/pose_tracker.cpp
  csrc/mmdeploy/codebase/mmpose/pose_tracker/pose_tracker.h
  csrc/mmdeploy/codebase/mmpose/pose_tracker/smoothing_filter.cpp
  csrc/mmdeploy/codebase/mmpose/pose_tracker/smoothing_filter.h
  csrc/mmdeploy/codebase/mmpose/pose_tracker/track.cpp
  csrc/mmdeploy/codebase/mmpose/pose_tracker/track.h
  csrc/mmdeploy/codebase/mmpose/pose_tracker/tracking_filter.cpp
  csrc/mmdeploy/codebase/mmpose/pose_tracker/tracking_filter.h
  csrc/mmdeploy/codebase/mmpose/pose_tracker/utils.cpp
  csrc/mmdeploy/codebase/mmpose/pose_tracker/utils.h
  csrc/mmdeploy/experimental/module_adapter.h
  csrc/mmdeploy/graph/inference.cpp
  csrc/mmdeploy/operation/cuda/crop_resize_pad.cpp
  csrc/mmdeploy/utils/opencv/opencv_utils.cpp
  demo/csrc/CMakeLists.txt
  demo/csrc/cpp/det_pose.cpp
  demo/csrc/cpp/pose_tracker.cpp
  demo/python/det_pose.py
  demo/python/pose_tracker.py
Labels: SDK

#1669 [Fix] fix coreml for branch 1.x
  mmdeploy/backend/coreml/backend_manager.py
  mmdeploy/backend/coreml/torchscript2coreml.py
  mmdeploy/pytorch/functions/topk.py
  tests/test_backend/test_wrapper.py
Labels: Bug:P0

#1689 [Enhancement] Add 320x320 static config for tensorrt
  configs/mmdet/detection/detection_tensorrt-fp16_static-320x320.py
  configs/mmdet/detection/detection_tensorrt-int8_static-320x320.py
  configs/mmdet/detection/detection_tensorrt_static-320x320.py
Labels: enhancement

#1684 [Fix] fix mmpose regression codec sdk export
  mmdeploy/codebase/mmpose/deploy/pose_detection.py
  mmdeploy/codebase/mmpose/deploy/pose_detection_model.py
Labels: bug

#1636 [Fix] fix rknn quantization pipeline
  mmdeploy/backend/rknn/backend_manager.py
  tools/deploy.py
Labels: bug, dev-1.x

#1667 [Fix] fix ascend
  docs/en/01-how-to-build/cmake_option.md
  docs/zh_cn/01-how-to-build/cmake_option.md
  mmdeploy/apis/visualize.py
  mmdeploy/backend/ascend/backend_manager.py
  mmdeploy/backend/ascend/wrapper.py
  mmdeploy/codebase/mmdet/core/post_processing/bbox_nms.py
  mmdeploy/codebase/mmdet/deploy/utils.py
  mmdeploy/codebase/mmdet/models/roi_heads/single_level_roi_extractor.py
Labels: Bug:P1
