Repository open-mmlab/mmdeploy, pull requests merged in 2023-02, with the labels that each got.

#1686 [Fix]fix trt nms jetson
  csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/allClassNMS.cu
Labels: Bug:P0

#1687 [Fix]fix nms trt jetson 1.x
  csrc/mmdeploy/backend_ops/tensorrt/common_impl/nms/allClassNMS.cu
Labels: Bug:P0

#1702 [Fix] import torchvision in wrapper
  mmdeploy/backend/torchscript/wrapper.py
Labels: Bug:P0

#1625 [Feature] Support feature map output for mmsegmentation
  csrc/mmdeploy/apis/c/mmdeploy/segmentor.cpp
  csrc/mmdeploy/apis/c/mmdeploy/segmentor.h
  csrc/mmdeploy/apis/csharp/MMDeploy.sln
  csrc/mmdeploy/apis/csharp/MMDeploy/APIs/Segmentor.cs
  csrc/mmdeploy/apis/python/segmentor.cpp
  csrc/mmdeploy/codebase/mmaction/CMakeLists.txt
  csrc/mmdeploy/codebase/mmaction/cpu/CMakeLists.txt
  csrc/mmdeploy/codebase/mmaction/cpu/format_shape_impl.cpp
  csrc/mmdeploy/codebase/mmaction/cuda/CMakeLists.txt
  csrc/mmdeploy/codebase/mmaction/cuda/format_shape_impl.cpp
  csrc/mmdeploy/codebase/mmaction/cuda/transpose.cu
  csrc/mmdeploy/codebase/mmaction/format_shape.cpp
  csrc/mmdeploy/codebase/mmaction/format_shape.h
  csrc/mmdeploy/codebase/mmaction/mmaction.h
  csrc/mmdeploy/codebase/mmseg/CMakeLists.txt
  csrc/mmdeploy/codebase/mmseg/mmseg.h
  csrc/mmdeploy/codebase/mmseg/segment.cpp
  csrc/mmdeploy/operation/cpu/CMakeLists.txt
  csrc/mmdeploy/operation/cpu/permute.cpp
  csrc/mmdeploy/operation/cuda/CMakeLists.txt
  csrc/mmdeploy/operation/cuda/permute.cpp
  csrc/mmdeploy/operation/cuda/permute.cu
  csrc/mmdeploy/operation/cuda/permute.h
  csrc/mmdeploy/operation/vision.cpp
  csrc/mmdeploy/operation/vision.h
  csrc/mmdeploy/utils/opencv/opencv_utils.cpp
  demo/csharp/image_segmentation/Program.cs
  demo/csrc/c/image_segmentation.cpp
  demo/csrc/cpp/segmentor.cxx
  demo/python/image_segmentation.py
  tests/test_csrc/preprocess/test_permute.cpp
Labels: enhancement

#1619 [Improvement] Better unit test.
  csrc/mmdeploy/backend_ops/tensorrt/roi_align/trt_roi_align.cpp
  mmdeploy/codebase/mmcls/models/utils/attention.py
  mmdeploy/codebase/mmdet3d/core/bbox/fcos3d_bbox_coder.py
  mmdeploy/core/rewriters/function_rewriter.py
  mmdeploy/core/rewriters/rewriter_utils.py
  mmdeploy/utils/test.py
  tests/test_apis/test_calibration.py
  tests/test_backend/test_wrapper.py
  tests/test_codebase/test_mmcls/conftest.py
  tests/test_codebase/test_mmcls/test_classification.py
  tests/test_codebase/test_mmcls/test_classification_model.py
  tests/test_codebase/test_mmcls/test_mmcls_models.py
  tests/test_codebase/test_mmdet/conftest.py
  tests/test_codebase/test_mmdet/test_mmdet_core.py
  tests/test_codebase/test_mmdet/test_mmdet_models.py
  tests/test_codebase/test_mmdet/test_mmdet_utils.py
  tests/test_codebase/test_mmdet/test_object_detection.py
  tests/test_codebase/test_mmdet/test_object_detection_model.py
  tests/test_codebase/test_mmdet3d/conftest.py
  tests/test_codebase/test_mmdet3d/test_mmdet3d_models.py
  tests/test_codebase/test_mmdet3d/test_monocular_detection.py
  tests/test_codebase/test_mmdet3d/test_monocular_detection_model.py
  tests/test_codebase/test_mmdet3d/test_voxel_detection.py
  tests/test_codebase/test_mmdet3d/test_voxel_detection_model.py
  tests/test_codebase/test_mmedit/conftest.py
  tests/test_codebase/test_mmedit/test_mmedit_models.py
  tests/test_codebase/test_mmedit/test_super_resolution.py
  tests/test_codebase/test_mmedit/test_super_resolution_model.py
  tests/test_codebase/test_mmocr/conftest.py
  tests/test_codebase/test_mmocr/test_mmocr_models.py
  tests/test_codebase/test_mmocr/test_text_detection.py
  tests/test_codebase/test_mmocr/test_text_detection_models.py
  tests/test_codebase/test_mmocr/test_text_recognition.py
  tests/test_codebase/test_mmocr/test_text_recognition_models.py
  tests/test_codebase/test_mmpose/conftest.py
  tests/test_codebase/test_mmpose/test_mmpose_models.py
  tests/test_codebase/test_mmpose/test_pose_detection.py
  tests/test_codebase/test_mmpose/test_pose_detection_model.py
  tests/test_codebase/test_mmrotate/conftest.py
  tests/test_codebase/test_mmrotate/test_mmrotate_core.py
  tests/test_codebase/test_mmrotate/test_mmrotate_models.py
  tests/test_codebase/test_mmrotate/test_rotated_detection.py
  tests/test_codebase/test_mmrotate/test_rotated_detection_model.py
  tests/test_codebase/test_mmseg/conftest.py
  tests/test_codebase/test_mmseg/test_mmseg_models.py
  tests/test_codebase/test_mmseg/test_segmentation.py
  tests/test_codebase/test_mmseg/test_segmentation_model.py
  tests/test_core/test_function_rewriter.py
  tests/test_core/test_module_rewriter.py
  tests/test_core/test_symbolic_register.py
  tests/test_mmcv/test_mmcv_cnn.py
  tests/test_mmcv/test_mmcv_ops.py
  tests/test_ops/__init__.py
  tests/test_ops/test_ops.py
  tests/test_ops/utils.py
  tests/test_pytorch/test_pytorch_functions.py
  tests/test_pytorch/test_pytorch_ops.py
  tests/test_utils/test_util.py
Labels: improvement

#1668 [Refactor] Support batch inference with shape clustering
  csrc/mmdeploy/net/net_module.cpp
Labels: SDK

#1748 [Fix] fix instance norm double free
  csrc/mmdeploy/backend_ops/tensorrt/instance_norm/trt_instance_norm.cpp
Labels: Bug:P0

#1749 [fix] Fix double free 1.x
  csrc/mmdeploy/backend_ops/tensorrt/instance_norm/trt_instance_norm.cpp
Labels: Bug:P0

#1745 [Fix] Fix `WarpBbox` and memory leak in `TextRecognizer`
  csrc/mmdeploy/apis/cxx/mmdeploy/text_recognizer.hpp
  csrc/mmdeploy/codebase/mmocr/warp.cpp
  csrc/mmdeploy/utils/opencv/opencv_utils.cpp
  demo/csrc/cpp/utils/visualize.h
Labels: Bug:P0, SDK

#1762 [Fix] remove score filtering in rtmdet_head rewriter since it leads to error shape in batch inference
  mmdeploy/codebase/mmdet/models/dense_heads/rtmdet_head.py
Labels: Bug:P1, dev-1.x

#1778 [Fix] Fix palette generation on opencv-3.x
  demo/csrc/cpp/utils/palette.h
Labels: Bug:P0

#1794 add `Model::ReadConfig` & simplify handle creation (#1738)
  csrc/mmdeploy/apis/c/mmdeploy/classifier.cpp
  csrc/mmdeploy/apis/c/mmdeploy/detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/pipeline.cpp
  csrc/mmdeploy/apis/c/mmdeploy/pipeline.h
  csrc/mmdeploy/apis/c/mmdeploy/pose_detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/restorer.cpp
  csrc/mmdeploy/apis/c/mmdeploy/rotated_detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/segmentor.cpp
  csrc/mmdeploy/apis/c/mmdeploy/text_detector.cpp
  csrc/mmdeploy/apis/c/mmdeploy/text_recognizer.cpp
  csrc/mmdeploy/apis/c/mmdeploy/video_recognizer.cpp
  csrc/mmdeploy/core/model.cpp
  csrc/mmdeploy/core/model.h
  csrc/mmdeploy/core/model_impl.h
  csrc/mmdeploy/graph/inference.cpp
  csrc/mmdeploy/model/CMakeLists.txt
  csrc/mmdeploy/model/directory_model_impl.cpp
  csrc/mmdeploy/model/zip_model_impl.cpp
Labels: enhancement

#1799 [Fix] Fix tensorrt int8
  mmdeploy/backend/tensorrt/utils.py
Labels: Bug:P1

#1802 [Fix] Fix missing include for gcc-10 build
  csrc/mmdeploy/core/mpl/type_traits.h
Labels: Bug:P1, SDK

#1797 [Fix] Avoid linking static libs in monolithic build
  csrc/mmdeploy/apis/cxx/CMakeLists.txt
Labels: Bug:P1

#1768 [Fix] fix centernet
  csrc/mmdeploy/preprocess/transform/default_format_bundle.cpp
  csrc/mmdeploy/preprocess/transform/pad.cpp
  mmdeploy/codebase/mmdet/models/__init__.py
  mmdeploy/codebase/mmdet/models/utils/__init__.py
  mmdeploy/codebase/mmdet/models/utils/gaussian_target.py
  tests/test_codebase/test_mmdet/test_mmdet_utils.py
Labels: Bug:P1

#1803 [Fix] disable building demos when preparing prebuilt package
  .github/workflows/backend-ascend.yml
  .github/workflows/backend-coreml.yml
  .github/workflows/backend-snpe.yml
  .github/workflows/linux-riscv64-gcc.yml
  cmake/MMDeployConfig.cmake.in
  csrc/mmdeploy/apis/cxx/CMakeLists.txt
  csrc/mmdeploy/apis/cxx/mmdeploy/common.hpp
  csrc/mmdeploy/apis/python/CMakeLists.txt
  tools/package_tools/configs/linux_x64.yaml
  tools/package_tools/configs/windows_x64.yaml
Labels: Bug:P1

#1810 disable building demos when preparing prebuilt package
  .github/workflows/backend-ascend.yml
  .github/workflows/backend-coreml.yml
  .github/workflows/backend-snpe.yml
  .github/workflows/linux-riscv64-gcc.yml
  cmake/MMDeployConfig.cmake.in
  csrc/mmdeploy/apis/cxx/CMakeLists.txt
  csrc/mmdeploy/apis/cxx/mmdeploy/common.hpp
  csrc/mmdeploy/apis/python/CMakeLists.txt
  tools/package_tools/configs/linux_x64.yaml
  tools/package_tools/configs/windows_x64.yaml
Labels: Bug:P1
